#include "types.h"

s32 OnGPHangRecover__11WiiPostProcFv(void) { return 0; }
s32 CheatPrint__22@unnamed@PostProc_cpp@FPCc(void) { return 0; }
s32 OnOverride__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnBloom__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnNoise__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnColorCorrect__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnChromatic__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnGradient__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnMotionBlur__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnToggleMotionBlur__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnLightTrails__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnKaleidoscope__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 OnRefraction__22@unnamed@PostProc_cpp@FP9DataArray(void) { return 0; }
s32 PreInit__11WiiPostProcFv(void) { return 0; }
s32 Init__11WiiPostProcFv(void) { return 0; }
s32 NewObject__11WiiPostProcFv(void) { return 0; }
s32 Terminate__11WiiPostProcFv(void) { return 0; }
s32 __ct__11WiiPostProcFv(void) { return 0; }
s32 __dt__11WiiPostProcFv(void) { return 0; }
s32 Select__11WiiPostProcFv(void) { return 0; }
s32 BeginWorld__11WiiPostProcFv(void) { return 0; }
s32 EndWorld__11WiiPostProcFv(void) { return 0; }
s32 DoPost__11WiiPostProcFv(void) { return 0; }
s32 DoPosterize__11WiiPostProcFv(void) { return 0; }
s32 DoHallOfTime__11WiiPostProcFv(void) { return 0; }
s32 DoGradient__11WiiPostProcFv(void) { return 0; }
s32 MotionBlur__11WiiPostProcFv(void) { return 0; }
s32 PrepareFinalTEV__11WiiPostProcFv(void) { return 0; }
s32 ClearFinalTEV__11WiiPostProcFv(void) { return 0; }
s32 DrawKaleidoscope__11WiiPostProcFv(void) { return 0; }
s32 Reset__11WiiPostProcFv(void) { return 0; }
s32 Vignette__11WiiPostProcFv(void) { return 0; }
s32 Priority__11WiiPostProcFv(void) { return 0; }
s32 SetType__11WiiPostProcF6Symbol(void) { return 0; }
s32 ClassName__11WiiPostProcCFv(void) { return 0; }
s32 @28@Priority__11WiiPostProcFv(void) { return 0; }
s32 @28@OnGPHangRecover__11WiiPostProcFv(void) { return 0; }
s32 @28@DoPost__11WiiPostProcFv(void) { return 0; }
s32 @28@EndWorld__11WiiPostProcFv(void) { return 0; }
s32 @28@BeginWorld__11WiiPostProcFv(void) { return 0; }
s32 @28@__dt__11WiiPostProcFv(void) { return 0; }
