#include "types.h"

s32 MCErrResult__25@unnamed@Memcard_Wii_cpp@Fl(void) { return 0; }
s32 Init__10MemcardWiiFv(void) { return 0; }
s32 Terminate__10MemcardWiiFv(void) { return 0; }
s32 DeleteContainer__10MemcardWiiFRC11ContainerId(void) { return 0; }
s32 CreateContainer__10MemcardWiiFRC11ContainerId(void) { return 0; }
s32 Mount__14MCContainerWiiF10CreateType(void) { return 0; }
s32 Unmount__14MCContainerWiiFv(void) { return 0; }
s32 GetPathFreeSpace__14MCContainerWiiFPCcPUx(void) { return 0; }
s32 GetDeviceFreeSpace__14MCContainerWiiFPUx(void) { return 0; }
s32 Delete__14MCContainerWiiFPCc(void) { return 0; }
s32 RemoveDir__14MCContainerWiiFPCc(void) { return 0; }
s32 MakeDir__14MCContainerWiiFPCc(void) { return 0; }
s32 GetSize__14MCContainerWiiFPCcPi(void) { return 0; }
s32 Format__14MCContainerWiiFv(void) { return 0; }
s32 Unformat__14MCContainerWiiFv(void) { return 0; }
s32 CreateMCFile__14MCContainerWiiFv(void) { return 0; }
s32 BuildPath__14MCContainerWiiFPCc(void) { return 0; }
s32 PrintDir__14MCContainerWiiFPCcb(void) { return 0; }
s32 __ct__9MCFileWiiFP11MCContainer(void) { return 0; }
s32 __dt__9MCFileWiiFv(void) { return 0; }
s32 Open__9MCFileWiiFPCc10AccessType10CreateType(void) { return 0; }
s32 Read__9MCFileWiiFPvi(void) { return 0; }
s32 Write__9MCFileWiiFPCvi(void) { return 0; }
s32 Seek__9MCFileWiiFi8SeekType(void) { return 0; }
s32 Close__9MCFileWiiFv(void) { return 0; }
s32 IsOpen__9MCFileWiiFv(void) { return 0; }
s32 CreateFile__9MCFileWiiFPCc(void) { return 0; }
s32 DeleteFile__9MCFileWiiFPCc(void) { return 0; }
s32 ValidateFile__9MCFileWiiFPCci(void) { return 0; }
s32 MakeString<PCc,Ul,i>__FPCcPCcUli_PCc(void) { return 0; }
s32 CheckTotalSpace__9MCFileWiiFii(void) { return 0; }
s32 CheckOpenSpace__9MCFileWiiFii(void) { return 0; }
s32 GetFreeUserBlocks__9MCFileWiiFv(void) { return 0; }
s32 GetFreeInodes__9MCFileWiiFv(void) { return 0; }
s32 __dt__14MCContainerWiiFv(void) { return 0; }
s32 __dt__10MemcardWiiFv(void) { return 0; }
s32 __sinit_\Memcard_Wii_cpp(void) { return 0; }
