#include "types.h"

s32 __ct__26StoreOfferContentsProviderFv(void) { return 0; }
s32 __dt__26StoreOfferContentsProviderFv(void) { return 0; }
s32 InitData__26StoreOfferContentsProviderFP6RndDir(void) { return 0; }
s32 Text__26StoreOfferContentsProviderCFiiP11UIListLabelP7UILabel(void) { return 0; }
s32 Mat__26StoreOfferContentsProviderCFiiP10UIListMesh(void) { return 0; }
s32 Custom__26StoreOfferContentsProviderCFiiP12UIListCustomPQ23Hmx6Object(void) { return 0; }
s32 DataSymbol__26StoreOfferContentsProviderCFi(void) { return 0; }
s32 IsActive__26StoreOfferContentsProviderCFi(void) { return 0; }
s32 NumData__26StoreOfferContentsProviderCFv(void) { return 0; }
s32 BuildList__26StoreOfferContentsProviderFP10StoreOfferQ226StoreOfferContentsProvider8ListType(void) { return 0; }
s32 ClearList__26StoreOfferContentsProviderFv(void) { return 0; }
s32 SetChecked__26StoreOfferContentsProviderFib(void) { return 0; }
s32 ToggleChecked__26StoreOfferContentsProviderFi(void) { return 0; }
s32 ToggleAllChecked__26StoreOfferContentsProviderFv(void) { return 0; }
s32 AcceptCurChecked__26StoreOfferContentsProviderFv(void) { return 0; }
s32 RefreshBlocks__26StoreOfferContentsProviderFv(void) { return 0; }
s32 SpecifyFirstSongContents__26StoreOfferContentsProviderFv(void) { return 0; }
s32 SpecifyNextSongContents__26StoreOfferContentsProviderFv(void) { return 0; }
s32 AnyChecked__26StoreOfferContentsProviderFv(void) { return 0; }
s32 AllChecked__26StoreOfferContentsProviderFv(void) { return 0; }
s32 NumChecked__26StoreOfferContentsProviderFv(void) { return 0; }
s32 Handle__26StoreOfferContentsProviderFP9DataArrayb(void) { return 0; }
s32 @28@InitData__26StoreOfferContentsProviderFP6RndDir(void) { return 0; }
s32 @28@IsActive__26StoreOfferContentsProviderCFi(void) { return 0; }
s32 @28@NumData__26StoreOfferContentsProviderCFv(void) { return 0; }
s32 @28@DataSymbol__26StoreOfferContentsProviderCFi(void) { return 0; }
s32 @28@Custom__26StoreOfferContentsProviderCFiiP12UIListCustomPQ23Hmx6Object(void) { return 0; }
s32 @28@Mat__26StoreOfferContentsProviderCFiiP10UIListMesh(void) { return 0; }
s32 @28@Text__26StoreOfferContentsProviderCFiiP11UIListLabelP7UILabel(void) { return 0; }
s32 @28@__dt__26StoreOfferContentsProviderFv(void) { return 0; }
