#include "types.h"

s32 __ct__18WiiFriendsProviderFv(void) { return 0; }
s32 __dt__18WiiFriendsProviderFv(void) { return 0; }
s32 Init__18WiiFriendsProviderFv(void) { return 0; }
s32 Type__24WiiFriendsListChangedMsgFv(void) { return 0; }
s32 Poll__18WiiFriendsProviderFv(void) { return 0; }
s32 Text__18WiiFriendsProviderCFiiP11UIListLabelP7UILabel(void) { return 0; }
s32 NumData__18WiiFriendsProviderCFv(void) { return 0; }
s32 SlotElementStateOverride__18WiiFriendsProviderCFiiP12UIListWidget17UIListWidgetState(void) { return 0; }
s32 EnumerateFriends__18WiiFriendsProviderFv(void) { return 0; }
s32 SetWiiFriend__18WiiFriendsProviderFi(void) { return 0; }
s32 GetFriendName__18WiiFriendsProviderFv(void) { return 0; }
s32 InviteFriend__18WiiFriendsProviderFv(void) { return 0; }
s32 SetName__6FriendF6String(void) { return 0; }
s32 SetGame__6FriendF6String(void) { return 0; }
s32 IsFriendOffline__18WiiFriendsProviderFv(void) { return 0; }
s32 IsFriendAlreadyInvited__18WiiFriendsProviderFv(void) { return 0; }
s32 IsInvitationPendingFromFriend__18WiiFriendsProviderFv(void) { return 0; }
s32 IsFriendInSession__18WiiFriendsProviderCFP9WiiFriend(void) { return 0; }
s32 IsPossessiveSuffixNeeded__18WiiFriendsProviderFPCc(void) { return 0; }
s32 GetPossessiveSuffix__18WiiFriendsProviderFPCc(void) { return 0; }
s32 GetPossessiveSuffix__18WiiFriendsProviderFP9WiiFriend(void) { return 0; }
s32 ClearInvitationSentStatus__18WiiFriendsProviderFP9WiiFriend(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC24WiiFriendsListChangedMsg(void) { return 0; }
s32 AreFriendsOrdered__FP9WiiFriendP9WiiFriend(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC25WiiFriendMgrOpCompleteMsg(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC17InviteReceivedMsg(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC16InviteExpiredMsg(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC16NewRemoteUserMsg(void) { return 0; }
s32 OnMsg__18WiiFriendsProviderFRC22SessionDisconnectedMsg(void) { return 0; }
s32 HandleNewFriendData__18WiiFriendsProviderFv(void) { return 0; }
s32 RefreshLists__18WiiFriendsProviderFv(void) { return 0; }
s32 Handle__18WiiFriendsProviderFP9DataArrayb(void) { return 0; }
s32 GotServerFriendData__18WiiFriendsProviderCFv(void) { return 0; }
s32 Type__25WiiFriendMgrOpCompleteMsgFv(void) { return 0; }
s32 __ct__25WiiFriendMgrOpCompleteMsgFP9DataArray(void) { return 0; }
s32 __ct__24WiiFriendsListChangedMsgFP9DataArray(void) { return 0; }
s32 __ct__25WiiFriendsDetailsProviderFv(void) { return 0; }
s32 __dt__25WiiFriendsDetailsProviderFv(void) { return 0; }
s32 Text__25WiiFriendsDetailsProviderCFiiP11UIListLabelP7UILabel(void) { return 0; }
s32 NumData__25WiiFriendsDetailsProviderCFv(void) { return 0; }
s32 SlotElementStateOverride__25WiiFriendsDetailsProviderCFiiP12UIListWidget17UIListWidgetState(void) { return 0; }
s32 SetWiiFriend__25WiiFriendsDetailsProviderFi(void) { return 0; }
s32 AreProfilesOrdered__FP16WiiFriendProfileP16WiiFriendProfile(void) { return 0; }
s32 EnumerateProfiles__25WiiFriendsDetailsProviderFv(void) { return 0; }
s32 OnMsg__25WiiFriendsDetailsProviderFRC24WiiFriendsListChangedMsg(void) { return 0; }
s32 Handle__25WiiFriendsDetailsProviderFP9DataArrayb(void) { return 0; }
s32 __ct__22WiiInvitationsProviderFv(void) { return 0; }
s32 __dt__22WiiInvitationsProviderFv(void) { return 0; }
s32 Init__22WiiInvitationsProviderFv(void) { return 0; }
s32 Text__22WiiInvitationsProviderCFiiP11UIListLabelP7UILabel(void) { return 0; }
s32 NumData__22WiiInvitationsProviderCFv(void) { return 0; }
s32 IsInvitationPending__22WiiInvitationsProviderFP9WiiFriend(void) { return 0; }
s32 SetInvitation__22WiiInvitationsProviderFi(void) { return 0; }
s32 AcceptInvitation__22WiiInvitationsProviderFP4User(void) { return 0; }
s32 DeclineInvitation__22WiiInvitationsProviderFv(void) { return 0; }
s32 EnumerateInvitations__22WiiInvitationsProviderFv(void) { return 0; }
s32 DeleteMessage__22WiiInvitationsProviderFi(void) { return 0; }
s32 OnMsg__22WiiInvitationsProviderFRC24WiiMessageListChangedMsg(void) { return 0; }
s32 OnMsg__22WiiInvitationsProviderFRC24WiiFriendsListChangedMsg(void) { return 0; }
s32 OnMsg__22WiiInvitationsProviderFRC25WiiFriendMgrOpCompleteMsg(void) { return 0; }
s32 OnMsg__22WiiInvitationsProviderFRC28EnumerateMessagesCompleteMsg(void) { return 0; }
s32 Handle__22WiiInvitationsProviderFP9DataArrayb(void) { return 0; }
s32 ClassName__25WiiFriendsDetailsProviderCFv(void) { return 0; }
s32 SetType__25WiiFriendsDetailsProviderF6Symbol(void) { return 0; }
s32 __sinit_\WiiFriendsProvider_cpp(void) { return 0; }
s32 @4@__dt__18WiiFriendsProviderFv(void) { return 0; }
s32 @4@Handle__18WiiFriendsProviderFP9DataArrayb(void) { return 0; }
s32 @4@__dt__25WiiFriendsDetailsProviderFv(void) { return 0; }
s32 @4@Handle__25WiiFriendsDetailsProviderFP9DataArrayb(void) { return 0; }
s32 @4@SetType__25WiiFriendsDetailsProviderF6Symbol(void) { return 0; }
s32 @4@ClassName__25WiiFriendsDetailsProviderCFv(void) { return 0; }
s32 @4@__dt__22WiiInvitationsProviderFv(void) { return 0; }
s32 @4@Handle__22WiiInvitationsProviderFP9DataArrayb(void) { return 0; }
