#include "types.h"

s32 CallGetConsoleUsernames__Q26Quazal32NintendoManagementProtocolClientFPQ26Quazal19ProtocolCallContextRCUxPQ26Quazal23qList<Q26Quazal6String>(void) { return 0; }
s32 ExtractCallSpecificResults__Q26Quazal32NintendoManagementProtocolClientFPQ26Quazal7MessagePQ26Quazal19ProtocolCallContext(void) { return 0; }
