#!/usr/bin/env python3
"""RB3 Web Port — Development Server with Asset Streaming API

Serves WASM build artifacts + streams game assets via HTTP API on localhost:8421.
(DC3's server runs on 8420; the disjoint port lets both run side-by-side.)
Sends required COOP/COEP headers for SharedArrayBuffer (future threading).

API endpoints:
  GET /api/health           — liveness probe (used by smoke-test waitForServer)
  GET /api/version          — asset version tag for IDB cache invalidation
  GET /api/manifest         — JSON list of all available assets
  GET /api/bundle           — single binary bundle of all .dta/.dtb (boot path)
  GET /api/bundle/boot      — binary bundle of the boot-critical .milo_xbox set
                              (R3: native/web/boot-assets.manifest)
  GET /api/bundle/screen/<name>
                            — per-screen dependency bundle (A2: the extra milos a
                              screen ENTER reads; native/web/screen-<name>.manifest)
  GET /api/file/<path>      — raw bytes of an extracted asset file
  GET /                     — index.html (build artifacts)
  GET /rb3-web.{js,wasm}    — WASM build output
"""

import argparse
import gzip as gzip_mod
import http.server
import json
import os
import random
import shutil
import subprocess
import sys
import urllib.parse

PORT = 8421
BUILD_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")
# R3 — boot-assets bundle manifest. A newline-delimited, comment-tolerant list of
# server-relative .milo_xbox paths the App ctor reads before the first interactive
# screen (see docs/native/web-perf-roadmap/R3-boot-bundle-expansion.md). Served as
# one async binary bundle by /api/bundle/boot so those reads hit warm MEMFS instead
# of freezing the wasm thread on a synchronous XHR. Generated, not hand-authored —
# scripts/web/gen-boot-manifest.mjs derives it from a cold-boot netperf waterfall.
BOOT_MANIFEST_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "boot-assets.manifest"
)
# A2 (incremental-load-perf PLAN.md T9) — per-screen dependency bundles. The
# boot bundle (above) pre-packs the App-ctor working set; these pack the EXTRA
# .milo_xbox/.dta the App reads when ENTERing a specific screen (main_hub,
# song_select, ...) so a first-visit transition lands those bytes in warm MEMFS
# instead of freezing the wasm thread on a per-file sync XHR. Same generated,
# comment-tolerant, newline-delimited format as the boot manifest. Served by
# /api/bundle/screen/<name> from native/web/screen-<name>.manifest, fired async
# at transition-START by main_web.cpp's screen-prewarm hook. Generated, not
# hand-authored: scripts/web/gen-boot-manifest.mjs --screen <name> distills the
# read set from a clean transition netlog (see the same script's header).
SCREEN_MANIFEST_DIR = os.path.dirname(os.path.abspath(__file__))
# Screen-name allowlist: the <name> in /api/bundle/screen/<name> must match this
# (a strict [a-z0-9_] form) so the route can never be coerced into a path-
# traversal of the manifest dir. Any name passing this still resolves to exactly
# native/web/screen-<name>.manifest; a missing manifest emits an empty bundle.
import re as _re
_SCREEN_NAME_RE = _re.compile(r"^[a-z0-9_]+$")
ASSETS_DIR = None  # Set via --assets-dir, RB3_ASSETS env, or auto-detect
# DTA overlay dir (native/dta/). Mirrors the native disk overlay in
# native/src/native_file.cpp: when an asset path is shadowed by an overlay
# file (native/dta/<path>), serve THAT file instead of the extracted original
# in both /api/file and /api/bundle, so the web build's MEMFS receives the
# overlay copy (e.g. config/joypad.dta with its button_meanings block). The
# extracted assets stay pristine. See docs/native/DTA_OVERLAY_ENGINE.md.
OVERLAY_DIR = None  # Set via --overlay-dir, RB3_DTA_OVERLAY env, or auto-detect
# A4 (incremental-load-perf research/12) — web texture downscale. A WEB-ONLY tree
# of venue .milo_xbox files with the top mip level stripped from each eligible
# BC/DXT texture (half-resolution, near-lossless — the remaining mips are
# pre-authored). It removes the brotli-incompressible BC bytes that dominate the
# venue milo WIRE (~44%), stacking on Wave 5's q11 (measured: the journey venue
# small_club_01 11.67 -> 4.88 MB q11, -58%). Generated by
# scripts/web/gen_web_downscaled.py into orig-assets/web-downscaled/ (gitignored
# build output, NOT the canonical extracted/ tree).
#
# When DOWNSCALE_ENABLED (RB3_WEB_DOWNSCALE / --downscale), /api/file resolves a
# request from this tree FIRST (a downscaled milo shadows the extracted original);
# else the existing extracted/ path is used unchanged. Default OFF — flipped on by
# the visual quality gate. The q11 prewarm walks this tree (prepended as a root)
# when the flag is on so the warmed wire bytes are the stripped+q11 size.
DOWNSCALE_DIR = None  # Set via --downscale-dir, RB3_WEB_DOWNSCALE_DIR, or auto-detect
DOWNSCALE_ENABLED = False  # RB3_WEB_DOWNSCALE / --downscale (default OFF)
# Optional fallback asset roots probed when a file is missing from ASSETS_DIR.
# W7-V4: album art (and other "long-tail" assets) live only in the full xbox
# extraction. The curated ASSETS_DIR is kept as the primary so on-disc smoke
# tests stay deterministic; the fallback fills the gap for art / chars / etc.
FALLBACK_ASSETS_DIRS = []
# Offline XMA->PCM sidecars (web-xma). These are content-hash-named flat
# <hex>.pcm files (~180MB total) that are NOT copied into the curated
# ASSETS_DIR or the wasm preload — they live in the gitignored derived tree
# and are served on demand here when the web build fetches one via
# /api/file/sfx/gen/xma_pcm/<hex>.pcm (lazily, one per distinct SFX that plays).
SIDECAR_DIR = None  # auto-detected (orig-assets/derived/sfx_pcm) or RB3_SFX_PCM_DIR

# R5 — on-demand wire compression for /api/file (see
# docs/native/web-perf-roadmap/R5-wire-compression.md). The big .milo_xbox
# assets are fetched via a *synchronous* XHR that freezes the wasm main thread
# for the whole transfer, so fewer wire bytes = proportionally less freeze.
# We compress compressible assets on demand with the brotli CLI (gzip fallback),
# cache the artifact to disk, and serve it via standard Content-Encoding
# negotiation — the browser decompresses before the engine's XHR sees the bytes,
# so this is fully transparent to the C++ engine (server.py-only change).
#
# Auto-detected at native/web/.cache/encoded/ (env RB3_ENCODE_CACHE,
# --encode-cache flag). Created on first use.
ENCODE_CACHE_DIR = None
ENCODE_ENABLED = True  # --no-encode disables (raw path, for A/B)
# Compressible asset extensions (scene-graph / DTA / object data). Deny wins
# over allow. Already-compressed payloads (.mogg/.ogg/.webm) gain ~0 and are
# explicitly denied — the mogg is R4's surface, never touched here.
#
# W5-T1 coverage expansion (research/08 §2 measurements, this machine):
#   .pcm      raw 16-bit XMA->PCM SFX sidecars — 59 MB/journey, served 100% raw
#             today; br q11 = 70-76% (q5 ~88%). The 10x lever (vorbis) is T2's
#             arm; q11 here is the RB3_SFX_OGG_OFF fallback so they're never raw.
#   .png_xbox/.bmp_xbox album art / textures — q11 ~70%.
#   .mid      song MIDI — q11 ~8% (highly compressible).
#   .txt      misc text — generically compressible.
# These were previously in the deny set and served raw.
COMPRESSIBLE_EXTS = {
    ".milo_xbox", ".milo", ".milo_ps3", ".milo_wii",
    ".dta", ".dtb", ".dtb_ps3",
    ".pcm", ".png_xbox", ".bmp_xbox", ".mid", ".txt",
}
INCOMPRESSIBLE_EXTS = {
    # Lossy/already-compressed media (measured br ratio ~100%): never compress.
    ".mogg", ".ogg", ".webm", ".jpg", ".jpeg", ".png", ".gz", ".br",
}
# brotli q5 keeps ~90% of q11's win at ~1/100th the CPU (colorpalettes 45.9% vs
# 40.3%, 0.23s vs 22.1s), and the cost is paid inline on the first (freezing)
# request — so q5 is the right on-demand default. q11 is reserved for the
# offline pre-warm (scripts/web/prewarm_encode_cache.py). gzip -6 is fallback.
ENCODE_LEVEL_BROTLI = 5
ENCODE_LEVEL_GZIP = 6
# Resolved encoder binaries (probed once in main()); None if absent.
BROTLI_BIN = None
GZIP_BIN = None


# ---------------------------------------------------------------------------
# Module-level encode primitives + bundle body builders.
#
# These are the ONE source of truth shared by the running server (RB3Handler)
# and the offline pre-warm (scripts/web/prewarm_encode_cache.py imports them).
# Keeping the bundle entry-set + fingerprint logic here — not duplicated in the
# script — is what guarantees the prewarmed bundle artifact has the exact same
# cache key the server looks for at request time (no fingerprint drift).
# ---------------------------------------------------------------------------


def encode_meta_text(src_size, src_mtime, enc=None, level=None):
    """Render a cache .meta line for a source of (size,mtime).

    Two forms, both keyed on the source identity:
      "<size>:<mtime>"              — legacy (pre-W5) q5 entry; level unknown.
      "<size>:<mtime>:<enc><level>" — W5 3-field; records the encode level so the
                                      pre-warm can decide whether to upgrade
                                      (e.g. "br11", "gz6").
    `enc`/`level` omitted ⇒ legacy 2-field form (back-compat writer)."""
    base = f"{src_size}:{int(src_mtime)}"
    if enc and level is not None:
        return f"{base}:{enc}{level}"
    return base


def parse_meta_text(text):
    """Parse a .meta line → (src_size:int, src_mtime:int, enc:str|None,
    level:int|None). Back-compat: a 2-field legacy entry returns (size, mtime,
    None, None) — the level is unknown, treated as the on-demand q5 default by
    callers. Returns None on a malformed line."""
    parts = (text or "").strip().split(":")
    if len(parts) < 2:
        return None
    try:
        size = int(parts[0])
        mtime = int(parts[1])
    except ValueError:
        return None
    enc, level = None, None
    if len(parts) >= 3 and parts[2]:
        tail = parts[2]
        # split a leading alpha encoder name from a trailing numeric level
        i = 0
        while i < len(tail) and tail[i].isalpha():
            i += 1
        enc = tail[:i] or None
        try:
            level = int(tail[i:]) if tail[i:] else None
        except ValueError:
            level = None
    return size, mtime, enc, level


def meta_is_valid_for(meta_text, src_size, src_mtime):
    """True if a .meta line describes the current source (size+mtime match).
    Back-compat: legacy 2-field q5 entries validate identically — the warm q5
    cache stays valid (NOT re-compressed) until the pre-warm upgrades it."""
    parsed = parse_meta_text(meta_text)
    if parsed is None:
        return False
    size, mtime, _enc, _level = parsed
    return size == src_size and mtime == int(src_mtime)


def _unlink_quiet(path):
    try:
        os.unlink(path)
    except OSError:
        pass


def _atomic_write(path, data):
    """Write `data` (bytes) to `path` atomically (unique temp + rename on the
    same filesystem). Returns True on success."""
    tmp = path + f".{os.getpid()}.{random.randrange(1 << 32):08x}.tmp"
    try:
        with open(tmp, "wb") as out:
            out.write(data)
        os.rename(tmp, path)
        return True
    except OSError:
        _unlink_quiet(tmp)
        return False


def encode_bytes(data, enc, level):
    """Compress `data` (bytes) via the brotli/gzip CLI at `level`. Returns the
    compressed bytes, or None on failure. enc ∈ {'br','gzip'}."""
    if enc == "br":
        if not BROTLI_BIN:
            return None
        cmd = [BROTLI_BIN, "-q", str(level), "-c"]
    elif enc == "gzip":
        if not GZIP_BIN:
            return None
        cmd = [GZIP_BIN, f"-{level}", "-c"]
    else:
        return None
    try:
        proc = subprocess.run(cmd, input=data, stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE)
    except OSError:
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def encode_file_to_cache(src_path, cache_path, enc, level):
    """Compress the file `src_path` into `cache_path` at `enc`/`level`, writing
    an atomic body + a 3-field `.meta` recording the source identity AND the
    encode level. Used by both the inline server path and the offline pre-warm,
    so the .meta level is always written (the server's old writer wrote a 2-field
    line; this writes 3-field — both validate the same way).

    Streams the brotli/gzip CLI src->stdout (avoids holding the body in RAM for
    big venue milos). Returns True on success, False on any failure (caller
    falls through to the raw path — no regression)."""
    cache_dir = os.path.dirname(cache_path)
    try:
        os.makedirs(cache_dir, exist_ok=True)
    except OSError:
        return False

    if enc == "br":
        if not BROTLI_BIN:
            return False
        cmd = [BROTLI_BIN, "-q", str(level), "-c", src_path]
    elif enc == "gzip":
        if not GZIP_BIN:
            return False
        cmd = [GZIP_BIN, f"-{level}", "-c", src_path]
    else:
        return False

    tmp_suffix = f".{os.getpid()}.{random.randrange(1 << 32):08x}.tmp"
    tmp_path = cache_path + tmp_suffix
    try:
        with open(tmp_path, "wb") as out:
            proc = subprocess.run(cmd, stdout=out, stderr=subprocess.PIPE)
        if proc.returncode != 0:
            _unlink_quiet(tmp_path)
            return False
        # Capture source identity BEFORE the rename so .meta describes the exact
        # bytes compressed (not a racing rewrite of the source).
        st = os.stat(src_path)
        os.rename(tmp_path, cache_path)
    except OSError:
        _unlink_quiet(tmp_path)
        return False

    meta_path = cache_path + ".meta"
    _atomic_write(meta_path,
                  encode_meta_text(st.st_size, st.st_mtime, enc, level).encode())
    return True


def serialize_bundle(entries):
    """Serialize bundle `entries` ([(rel, bytes), ...]) into the binary bundle
    body the engine's onBundleSuccess parses:
        uint32 count, then per file: uint32 path_len, path, uint32 data_len, data
    Integers little-endian (Emscripten host order). Entries are sorted by path
    for a stable body. ONE source of truth — used by the server and the pre-warm
    so both produce byte-identical bodies (and thus identical fingerprints)."""
    import struct
    entries = sorted(entries, key=lambda x: x[0])
    chunks = [struct.pack("<I", len(entries))]
    for path, data in entries:
        path_bytes = path.encode("utf-8")
        chunks.append(struct.pack("<I", len(path_bytes)))
        chunks.append(path_bytes)
        chunks.append(struct.pack("<I", len(data)))
        chunks.append(data)
    return b"".join(chunks)


def bundle_fingerprint(entries):
    """16-hex fingerprint of a bundle's entry set+sizes (cheap — no payload
    hash). A changed asset set / size rebuilds the cached artifact. Entries are
    sorted to match serialize_bundle so the fingerprint is order-independent.
    ONE source of truth — the server's request-time key and the pre-warm's
    written key MUST agree."""
    import hashlib
    ents = sorted(entries, key=lambda x: x[0])
    return hashlib.sha1(
        (f"{len(ents)}|" + "|".join(
            f"{r}:{len(d)}" for r, d in ents)).encode()
    ).hexdigest()[:16]


def overlay_path(safe_rel):
    """Overlay file path for a relative asset path if an overlay shadows it, else
    None. Module-level twin of RB3Handler._overlay_path so the offline pre-warm
    resolves bundle entries identically to the server."""
    if not OVERLAY_DIR or ".." in safe_rel.replace("\\", "/").split("/"):
        return None
    cand = os.path.join(OVERLAY_DIR, safe_rel)
    return cand if os.path.isfile(cand) else None


def downscale_path(safe_rel):
    """A4 — web-downscaled file path for a relative asset path if the downscale is
    enabled AND a stripped copy exists, else None. The downscaled tree mirrors the
    request key, so the lookup is a direct join (e.g.
    "world/venue/small_club/small_club_01/gen/small_club_01.milo_xbox"). Only ever
    shadows venue milos the generator wrote; anything else falls through to the
    canonical extracted tree. A ".." key is rejected to keep the lookup strictly
    inside the downscale tree."""
    if not (DOWNSCALE_ENABLED and DOWNSCALE_DIR):
        return None
    if ".." in safe_rel.replace("\\", "/").split("/"):
        return None
    cand = os.path.join(DOWNSCALE_DIR, safe_rel)
    return cand if os.path.isfile(cand) else None


def resolve_asset_path(rel):
    """Resolve a server-relative asset path to an on-disk file: downscale (A4) →
    overlay → ASSETS_DIR → the "(..)/(..)" system/run layout → fallback roots.
    Returns the absolute path or None. Module-level twin of
    RB3Handler._resolve_asset_path — ONE source of truth shared by the server
    bundle routes and the pre-warm so the entry sets (and thus the bundle
    fingerprint) never drift. The downscale probe is FIRST so a stripped venue
    milo shadows the extracted original when the flag is on (else it's a no-op)."""
    full_path = downscale_path(rel) or overlay_path(rel) or os.path.join(ASSETS_DIR, rel)
    if not os.path.isfile(full_path) and rel.startswith("system/"):
        alt = os.path.join(ASSETS_DIR, "(..)", "(..)", rel)
        if os.path.isfile(alt):
            full_path = alt
    if not os.path.isfile(full_path):
        for fb_root in FALLBACK_ASSETS_DIRS:
            fb_path = os.path.join(fb_root, rel)
            if os.path.isfile(fb_path):
                full_path = fb_path
                break
            if rel.startswith("system/"):
                fb_alt = os.path.join(fb_root, "(..)", "(..)", rel)
                if os.path.isfile(fb_alt):
                    full_path = fb_alt
                    break
    return full_path if os.path.isfile(full_path) else None


def read_manifest(manifest_path):
    """Newline-delimited, comment-tolerant manifest → [server-relative paths].
    Module-level twin of RB3Handler._read_manifest."""
    paths = []
    try:
        with open(manifest_path, "r") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                paths.append(line)
    except OSError:
        pass
    return paths


def build_config_bundle_entries():
    """Build the /api/bundle (config DTA/DTB) entry set exactly as the server's
    _serve_bundle does — walks ASSETS_DIR for .dta/.dtb, restores "(..)"→"..",
    applies the DTA overlay. Returns [(rel, bytes), ...]."""
    BUNDLE_EXTS = {".dta", ".dtb"}
    entries = []
    for root, _dirs, filenames in os.walk(ASSETS_DIR):
        for f in filenames:
            _name, ext = os.path.splitext(f)
            if ext.lower() not in BUNDLE_EXTS:
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, ASSETS_DIR).replace("(..)", "..")
            ov = overlay_path(rel)
            src = ov if ov else full
            with open(src, "rb") as fh:
                entries.append((rel, fh.read()))
    return entries


def build_manifest_bundle_entries(manifest_path):
    """Build a boot / per-screen bundle entry set from a manifest, resolving each
    path with resolve_asset_path (skipping the unresolved, as the server does).
    Returns [(rel, bytes), ...]."""
    entries = []
    for rel in read_manifest(manifest_path):
        full = resolve_asset_path(rel)
        if not full:
            continue
        with open(full, "rb") as fh:
            entries.append((rel, fh.read()))
    return entries


class RB3Handler(http.server.SimpleHTTPRequestHandler):
    """Serves static files from build/ with correct MIME types, security headers,
    and an asset streaming API backed by a pre-extracted game data directory."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=BUILD_DIR, **kwargs)

    def end_headers(self):
        # Required for SharedArrayBuffer (future pthreads support)
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cross-Origin-Resource-Policy", "cross-origin")
        self.send_header("Cache-Control", self._cache_control_for_path())
        super().end_headers()

    def _cache_control_for_path(self):
        """Per-path HTTP cache policy. Centralized here so every response path
        (static, precompressed, asset API) gets a consistent header.

        The two deployable builds are served from distinct subdirs so caching can
        be decided purely from the request path (the client picks the subdir via
        the ?debug=true URL param — see native/web/index.html):

          /release/*  → long-lived immutable cache. index.html version-busts the
                        URL with ?v=<asset+wasm mtime> from /api/version, so a
                        rebuilt release wasm gets a new URL and the browser reuses
                        the cached + already-compiled wasm on every reload in
                        between. THIS is what makes reloads fast.
          /debug/*    → never cached. Fast-iteration build; always fresh.
          /api/version→ never cached, or the cache-bust token itself goes stale.
          everything else (index.html, audio-worklet.js, /api/bundle, manifest)
                      → revalidate each load so edits/rebuilds propagate.
        """
        path = urllib.parse.urlparse(self.path).path
        if path.startswith("/release/"):
            # Safe to cache hard: the URL is version-stamped, so a new build is a
            # new URL. 1 year + immutable = zero revalidation round-trips.
            return "public, max-age=31536000, immutable"
        if path.startswith("/debug/") or path == "/api/version":
            return "no-cache, no-store, must-revalidate"
        return "no-cache"

    def guess_type(self, path):
        if path.endswith(".wasm"):
            return "application/wasm"
        if path.endswith(".js"):
            return "application/javascript"
        if path.endswith(".dta"):
            return "text/plain"
        if path.endswith(".webm"):
            return "video/webm"
        return super().guess_type(path)

    def do_GET(self):
        if self.path.startswith("/api/"):
            self._handle_api()
            return
        if self.path == "/":
            self.path = "/index.html"
        if self._maybe_serve_precompressed():
            return
        super().do_GET()

    def do_HEAD(self):
        if self.path.startswith("/api/"):
            self._handle_api()
            return
        if self.path == "/":
            self.path = "/index.html"
        if self._maybe_serve_precompressed(head_only=True):
            return
        super().do_HEAD()

    def _maybe_serve_precompressed(self, head_only=False):
        """W4a — serve a pre-compressed .br or .gz next to the requested
        .wasm / .js when the client advertises support. Returns True if a
        response was sent (caller should bail out). The .br/.gz artifacts are
        generated by scripts/web/build.sh; if missing we fall through to the
        raw file (no on-the-fly compression — too slow at q11 per request)."""
        # Only short-circuit for the two big payloads. Everything else (API,
        # assets, etc.) keeps the existing identity path. Strip the ?query FIRST
        # — release URLs carry a ?v=<version> cache-bust token, so the suffix
        # check has to run against the path without it (else br/gz is skipped).
        url_path = urllib.parse.urlparse(self.path).path
        if not (url_path.endswith(".wasm") or url_path.endswith(".js")):
            return False
        rel = url_path.lstrip("/")
        base_path = os.path.join(BUILD_DIR, rel)
        accept = (self.headers.get("Accept-Encoding") or "").lower()
        candidates = []
        if "br" in accept:
            candidates.append((base_path + ".br", "br"))
        if "gzip" in accept:
            candidates.append((base_path + ".gz", "gzip"))
        for disk_path, enc in candidates:
            if os.path.isfile(disk_path):
                self._serve_encoded(disk_path, base_path, enc, head_only)
                return True
        return False

    def _serve_encoded(self, disk_path, base_path, encoding, head_only):
        """Serve a pre-compressed file with the matching Content-Encoding.
        Content-Type follows the *base* (.wasm / .js) so the browser parses
        it correctly after decompression."""
        size = os.path.getsize(disk_path)
        ctype = self.guess_type(base_path)
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Encoding", encoding)
        self.send_header("Content-Length", str(size))
        self.send_header("Vary", "Accept-Encoding")
        self.end_headers()
        if head_only:
            return
        with open(disk_path, "rb") as f:
            while True:
                chunk = f.read(65536)
                if not chunk:
                    break
                self.wfile.write(chunk)

    def _maybe_compressed_asset(self, full_path, safe_rel, head_only):
        """R5 — on-demand wire compression for /api/file. If `full_path` is a
        compressible asset and the client advertises br/gzip, compress it once
        into ENCODE_CACHE_DIR (atomic temp+rename) and serve the cached artifact
        with the matching Content-Encoding. Returns True if a response was sent
        (caller bails), False to fall through to the raw path.

        Transparent to the engine: the browser decompresses Content-Encoding
        before the wasm XHR/fetch sees the bytes, so the C++ side still receives
        the original uncompressed milo. See R5-wire-compression.md.

        Bails (→ raw path) for: compression disabled, a Range request (Range ⊕
        Content-Encoding is invalid), no encoder available, an ext not in the
        allowlist or in the deny set, or a client that advertised neither br nor
        gzip. The raw fallback guarantees no regression."""
        if not (ENCODE_ENABLED and ENCODE_CACHE_DIR):
            return False
        if self.headers.get("Range"):
            return False
        # Deny wins over allow. Lowercase the extension for the membership test.
        _root, ext = os.path.splitext(safe_rel)
        ext = ext.lower()
        if ext in INCOMPRESSIBLE_EXTS or ext not in COMPRESSIBLE_EXTS:
            return False

        accept = (self.headers.get("Accept-Encoding") or "").lower()
        # Prefer brotli over gzip; intersect preference with the client's
        # Accept-Encoding and with which encoder binaries actually resolved.
        if "br" in accept and BROTLI_BIN:
            enc, cache_ext = "br", ".br"
        elif "gzip" in accept and GZIP_BIN:
            enc, cache_ext = "gzip", ".gz"
        else:
            return False

        cache_path = os.path.join(ENCODE_CACHE_DIR, safe_rel + cache_ext)
        # mtime/size-keyed staleness: if the cached artifact predates the source
        # or the source changed, recompress. A sidecar .meta records (size,mtime)
        # of the source the artifact was built from; cheap stat-and-compare.
        if not self._encoded_cache_valid(cache_path, full_path):
            if not self._encode_to_cache(full_path, cache_path, enc):
                return False  # encode failed → fall through to raw
        # Final safety: a cache entry must exist and be non-stale now. If a
        # concurrent purge/race left it missing, fall through to raw rather than
        # 500.
        if not os.path.isfile(cache_path):
            return False

        self._serve_encoded(cache_path, full_path, enc, head_only)
        return True

    @staticmethod
    def _encoded_cache_valid(cache_path, src_path):
        """True if `cache_path` exists and was built from the current `src_path`
        (size + mtime match the sidecar .meta). Recompress on any drift.

        Back-compat: validates BOTH the legacy 2-field (`size:mtime`, q5) and the
        W5 3-field (`size:mtime:<enc><level>`) .meta forms — see
        meta_is_valid_for — so the warm pre-W5 q5 cache stays valid (never
        re-compressed inline) until the offline pre-warm upgrades it to q11."""
        if not os.path.isfile(cache_path):
            return False
        meta_path = cache_path + ".meta"
        try:
            st = os.stat(src_path)
            with open(meta_path, "r") as fh:
                meta = fh.read().strip()
        except OSError:
            return False
        return meta_is_valid_for(meta, st.st_size, st.st_mtime)

    def _encode_to_cache(self, src_path, cache_path, enc):
        """Compress `src_path` into `cache_path` at the on-demand q5 level via the
        shared encode_file_to_cache primitive (atomic body + 3-field .meta).

        The server is a ThreadingHTTPServer, so two requests can miss the same
        asset at once; the atomic rename guarantees a reader never sees a
        half-written body and a duplicate compress loses the rename race
        harmlessly. Returns True on success, False on any failure (caller falls
        through to the raw path — no regression)."""
        level = ENCODE_LEVEL_BROTLI if enc == "br" else ENCODE_LEVEL_GZIP
        return encode_file_to_cache(src_path, cache_path, enc, level)

    @staticmethod
    def _unlink_quiet(path):
        _unlink_quiet(path)

    def _handle_api(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path == "/api/health":
            self._serve_health()
        elif path == "/api/version":
            self._serve_version()
        elif path == "/api/manifest":
            self._serve_manifest()
        elif path == "/api/bundle/boot":
            self._serve_boot_bundle()
        elif path.startswith("/api/bundle/screen/"):
            self._serve_screen_bundle(path[len("/api/bundle/screen/"):])
        elif path == "/api/bundle":
            self._serve_bundle()
        elif path.startswith("/api/file/"):
            rel = path[len("/api/file/"):]
            self._serve_asset_file(rel)
        else:
            self._json_error(404, "Unknown API endpoint")

    def _serve_health(self):
        body = json.dumps({"status": "ok"}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _serve_version(self):
        """Asset version tag for client-side IDB cache invalidation.

        Combines the assets-dir mtime and the WASM build mtime so the cache
        is dropped when either the asset set or the engine changes. The tag
        is opaque — clients only compare for equality.
        """
        parts = []
        if ASSETS_DIR and os.path.isdir(ASSETS_DIR):
            try:
                parts.append(str(int(os.path.getmtime(ASSETS_DIR))))
            except OSError:
                parts.append("0")
        else:
            parts.append("noassets")
        # Prefer the release wasm mtime (that's the cached, version-busted build);
        # fall back to debug, then the legacy flat path. Bumping the release wasm
        # changes this token → index.html appends a fresh ?v= → cache is busted.
        wasm_path = None
        for cand in ("release/rb3-web.wasm", "debug/rb3-web.wasm", "rb3-web.wasm"):
            p = os.path.join(BUILD_DIR, cand)
            if os.path.isfile(p):
                wasm_path = p
                break
        if wasm_path:
            try:
                parts.append(str(int(os.path.getmtime(wasm_path))))
            except OSError:
                parts.append("0")
        else:
            parts.append("nowasm")
        version = "-".join(parts)
        body = json.dumps({"version": version}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _serve_manifest(self):
        if not ASSETS_DIR:
            self._json_error(503, "No assets directory configured")
            return

        files = []
        for root, _dirs, filenames in os.walk(ASSETS_DIR):
            for f in filenames:
                full = os.path.join(root, f)
                rel = os.path.relpath(full, ASSETS_DIR)
                files.append({"path": rel, "size": os.path.getsize(full)})

        files.sort(key=lambda x: x["path"])
        body = json.dumps({"files": files, "count": len(files)}, indent=1).encode()
        # W5-T1 — the manifest is on the boot critical path (rb3_pre.js races it
        # against the wasm compile). ~462 KB raw JSON → ~50 KB br. Serve it
        # through the same Content-Encoding negotiation as the bundles (in-memory
        # compress; the browser decodes before the JSON parse, transparent).
        self._serve_json_body(body)

    def _serve_json_body(self, body):
        """Serve an in-memory JSON `body` (bytes) with Content-Encoding
        negotiation (br/gzip via the shared encode_bytes), falling back to raw
        on HEAD / no-encoder / encode-failure. Small bodies are compressed
        inline every request (cheap: <1 ms for tens of KB at q5)."""
        enc, _cache_ext = self._pick_encoding()
        if enc and self.command != "HEAD":
            level = ENCODE_LEVEL_BROTLI if enc == "br" else ENCODE_LEVEL_GZIP
            comp = encode_bytes(body, enc, level)
            if comp is not None:
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Encoding", enc)
                self.send_header("Content-Length", str(len(comp)))
                self.send_header("Vary", "Accept-Encoding")
                self.end_headers()
                self.wfile.write(comp)
                return
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Vary", "Accept-Encoding")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    @staticmethod
    def _overlay_path(safe_rel):
        """Overlay file path for a relative asset path if an overlay shadows it,
        else None. Delegates to the module-level overlay_path (one source of
        truth shared with the offline pre-warm); the overlay is keyed on the
        archive-relative layout (e.g. "config/joypad.dta") and a ".." key is
        rejected to keep the overlay strictly inside native/dta/."""
        return overlay_path(safe_rel)

    def _emit_bundle(self, entries, cache_name=None):
        """Write `entries` ([(rel, bytes), ...]) as the binary bundle the engine's
        onBundleSuccess (milo-native-engine/src/platform/WebAssets.cpp) parses.

        Format: uint32 count, then for each file:
          uint32 path_len, path (UTF-8), uint32 data_len, data (bytes)
        Integers are little-endian (Emscripten host order).

        Shared by /api/bundle (the .dta/.dtb config bundle) and /api/bundle/boot
        (the R3 boot-milo bundle). Entries are emitted sorted by path for a stable
        body. HEAD sends headers only.

        R3<->R5 fix: when `cache_name` is given and the client accepts br/gzip, the
        bundle body is compressed on the wire (Content-Encoding) with a persistent
        disk cache. Without this the boot bundle shipped ~60 MB RAW — bypassing
        R5's per-file compression and putting the full uncompressed transfer on the
        cold-boot critical path. The browser decodes Content-Encoding before the
        engine's fetch sees the bytes, so onBundleSuccess still parses the raw
        bundle (transparent, same as /api/file).

        Body + fingerprint come from the module-level serialize_bundle /
        bundle_fingerprint so the offline pre-warm produces byte-identical
        artifacts under the SAME cache key (no fingerprint drift)."""
        body = serialize_bundle(entries)

        enc, cache_ext = self._pick_encoding()
        if enc and cache_name and self.command != "HEAD":
            fp = bundle_fingerprint(entries)
            comp = self._bundle_encoded(cache_name, fp, body, enc, cache_ext)
            if comp is not None:
                self.send_response(200)
                self.send_header("Content-Type", "application/octet-stream")
                self.send_header("Content-Encoding", enc)
                self.send_header("Content-Length", str(len(comp)))
                self.send_header("Vary", "Accept-Encoding")
                self.end_headers()
                self.wfile.write(comp)
                return

        # Raw fallback (HEAD, no encoder advertised, or encode failed).
        self.send_response(200)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Vary", "Accept-Encoding")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _pick_encoding(self):
        """('br'|'gzip', ext) per Accept-Encoding + available encoders + the
        ENCODE_ENABLED toggle, else (None, None). Prefers brotli. Mirrors the
        negotiation in _maybe_compressed_asset for the in-memory bundle path."""
        if not (ENCODE_ENABLED and ENCODE_CACHE_DIR):
            return None, None
        accept = (self.headers.get("Accept-Encoding") or "").lower()
        if "br" in accept and BROTLI_BIN:
            return "br", ".br"
        if "gzip" in accept and GZIP_BIN:
            return "gzip", ".gz"
        return None, None

    def _bundle_encoded(self, cache_name, fp, body, enc, cache_ext):
        """Get-or-build the compressed bundle artifact, cached under
        ENCODE_CACHE_DIR/_bundles/<name>.<fp><ext> (the fingerprint is in the
        filename, so a changed asset set rebuilds). On a miss, compresses the
        in-memory body at the server's on-demand level (q5) via the shared
        encode_bytes; the offline pre-warm writes the SAME path at q11, so a
        prewarmed bundle is served straight from disk here. Returns the
        compressed bytes, or None on failure (caller serves raw — no
        regression)."""
        try:
            cache_dir = os.path.join(ENCODE_CACHE_DIR, "_bundles")
            os.makedirs(cache_dir, exist_ok=True)
        except OSError:
            return None
        cache_path = os.path.join(cache_dir, f"{cache_name}.{fp}{cache_ext}")
        if os.path.isfile(cache_path):
            try:
                with open(cache_path, "rb") as fh:
                    return fh.read()
            except OSError:
                pass  # fall through and rebuild
        level = ENCODE_LEVEL_BROTLI if enc == "br" else ENCODE_LEVEL_GZIP
        comp = encode_bytes(body, enc, level)
        if comp is None:
            return None
        _atomic_write(cache_path, comp)  # atomic; duplicate builders race harmlessly
        return comp

    def _serve_bundle(self):
        """All boot-path DTA/DTB files as a single binary bundle (see
        _emit_bundle for the format)."""
        if not ASSETS_DIR:
            self._json_error(503, "No assets directory configured")
            return

        # Entry set comes from the module-level builder (one source of truth
        # shared with the offline pre-warm so the bundle fingerprint never drifts).
        self._emit_bundle(build_config_bundle_entries(), cache_name="config")

    def _resolve_asset_path(self, rel):
        """Resolve a server-relative asset path to an on-disk file, mirroring
        _serve_asset_file's resolution order: DTA overlay → curated ASSETS_DIR →
        the "(..)/(..)" system/run layout → the fallback asset roots. Delegates
        to the module-level resolve_asset_path (one source of truth with the
        offline pre-warm)."""
        return resolve_asset_path(rel)

    @staticmethod
    def _read_manifest(manifest_path):
        """Newline-delimited, comment-tolerant manifest → [server-relative paths].
        Delegates to the module-level read_manifest."""
        return read_manifest(manifest_path)

    @classmethod
    def _read_boot_manifest(cls):
        """Read native/web/boot-assets.manifest → list of server-relative paths."""
        return read_manifest(BOOT_MANIFEST_PATH)

    def _serve_boot_bundle(self):
        """R3 — the boot-critical .milo_xbox working set as one binary bundle.

        Reads native/web/boot-assets.manifest, resolves each path with the same
        overlay/fallback/"(..)" logic as /api/file, and emits the shared bundle
        format. A manifest entry that resolves to nothing is logged and SKIPPED
        (mirroring onBundleSuccess's skip-on-write-fail tolerance) so one missing
        asset never fails the whole boot bundle — the client's sync path is the
        backstop for anything not delivered here."""
        if not ASSETS_DIR:
            self._json_error(503, "No assets directory configured")
            return

        entries = []
        missing = 0
        for rel in self._read_boot_manifest():
            full = self._resolve_asset_path(rel)
            if not full:
                missing += 1
                self.log_message("boot-bundle: missing %s (skipped)", rel)
                continue
            with open(full, "rb") as fh:
                data = fh.read()
            entries.append((rel, data))

        total = sum(len(d) for _r, d in entries)
        self.log_message(
            "boot-bundle: %d files, %.1f MB%s",
            len(entries), total / 1e6,
            (f", {missing} missing" if missing else ""),
        )
        self._emit_bundle(entries, cache_name="boot")

    def _serve_screen_bundle(self, name):
        """A2 — a single named screen's dependency working set as one binary
        bundle (the format _emit_bundle produces, identical to the boot bundle).

        `name` is the screen identifier from /api/bundle/screen/<name> (e.g.
        "main_hub" or "song_select"); it is validated against _SCREEN_NAME_RE so
        it can only ever resolve to native/web/screen-<name>.manifest (no path
        traversal). A missing or empty manifest emits an EMPTY bundle (count=0) —
        the client unpacks nothing and the engine's per-file sync path remains the
        backstop, so an unknown/absent screen never errors the transition.

        Freshness matches the boot bundle exactly: _emit_bundle fingerprints the
        entry set+sizes into the cache key, so a changed manifest (or a changed
        asset behind it) rebuilds the compressed artifact. Each screen gets its
        own cache_name so the bundles never collide in the _bundles cache dir."""
        if not ASSETS_DIR:
            self._json_error(503, "No assets directory configured")
            return
        if not _SCREEN_NAME_RE.match(name or ""):
            self._json_error(400, "Invalid screen name")
            return

        manifest_path = os.path.join(SCREEN_MANIFEST_DIR, f"screen-{name}.manifest")
        entries = []
        missing = 0
        for rel in self._read_manifest(manifest_path):
            full = self._resolve_asset_path(rel)
            if not full:
                missing += 1
                self.log_message("screen-bundle[%s]: missing %s (skipped)", name, rel)
                continue
            with open(full, "rb") as fh:
                data = fh.read()
            entries.append((rel, data))

        total = sum(len(d) for _r, d in entries)
        self.log_message(
            "screen-bundle[%s]: %d files, %.1f MB%s",
            name, len(entries), total / 1e6,
            (f", {missing} missing" if missing else ""),
        )
        # cache_name is per-screen so each screen's compressed artifact is
        # distinct; the fingerprint inside _emit_bundle still rebuilds on drift.
        self._emit_bundle(entries, cache_name=f"screen-{name}")

    def _serve_asset_file(self, relpath):
        if not ASSETS_DIR:
            self._json_error(503, "No assets directory configured")
            return

        relpath = urllib.parse.unquote(relpath)
        safe = os.path.normpath(relpath)
        if safe.startswith("..") or os.path.isabs(safe):
            self._json_error(403, "Path traversal denied")
            return

        # A4 web downscale: a web-downscaled/<path> stripped venue milo shadows the
        # extracted original when RB3_WEB_DOWNSCALE is on (default OFF). Probed
        # FIRST so the wire serves the smaller mip-stripped bytes; a no-op (returns
        # None) when the flag is off or no stripped copy exists. Transparent to the
        # engine (same milo format, fewer mips — CopyBottomMip/UseBottomMip path).
        #
        # DTA overlay: a native/dta/<path> file shadows the extracted original
        # for on-demand /api/file fetches too (the boot bundle covers the boot
        # path; this covers any lazily-fetched config DTA). Checked after downscale.
        full_path = (downscale_path(safe) or self._overlay_path(safe)
                     or os.path.join(ASSETS_DIR, safe))

        # Ark extraction stores ".." as "(..)" in directory names.
        # Files under system/run/ live at (..)/(..)/system/run/ on disk.
        if not os.path.isfile(full_path) and safe.startswith("system/"):
            alt = os.path.join(ASSETS_DIR, "(..)", "(..)", safe)
            if os.path.isfile(alt):
                full_path = alt

        # W7-V4: long-tail asset fallback (album art, character textures, etc.)
        # The curated ASSETS_DIR doesn't ship per-song _keep.png_xbox files —
        # only the full xbox extraction does. Probe the configured fallback
        # roots before 404-ing so song_select can render real cover art.
        if not os.path.isfile(full_path):
            for fb_root in FALLBACK_ASSETS_DIRS:
                fb_path = os.path.join(fb_root, safe)
                if os.path.isfile(fb_path):
                    full_path = fb_path
                    break
                if safe.startswith("system/"):
                    fb_alt = os.path.join(fb_root, "(..)", "(..)", safe)
                    if os.path.isfile(fb_alt):
                        full_path = fb_alt
                        break

        # web-xma: offline XMA->PCM sidecars. They are served from the gitignored
        # derived tree (orig-assets/derived/sfx_pcm) on demand rather than copied
        # into ASSETS_DIR or the wasm preload. The runtime asks for them at
        # sfx/gen/xma_pcm/<hex>.pcm; the on-disk files are flat <hex>.pcm, so the
        # basename is the lookup key. normpath/`..` guard above already ran, so the
        # basename is safe. A fresh checkout without sidecars just falls through to
        # the 404 below (no regression).
        if not os.path.isfile(full_path) and SIDECAR_DIR and "xma_pcm/" in safe:
            sc_path = os.path.join(SIDECAR_DIR, os.path.basename(safe))
            if os.path.isfile(sc_path):
                full_path = sc_path

        if not os.path.isfile(full_path):
            self._json_error(404, f"Not found: {relpath}")
            return

        size = os.path.getsize(full_path)
        content_type = self.guess_type(full_path)
        head_only = self.command == "HEAD"

        range_hdr = self.headers.get("Range")
        if range_hdr and not head_only:
            self._serve_range(full_path, size, range_hdr, content_type)
            return

        # R5 — on-demand wire compression. Compress + cache compressible assets
        # (.milo_xbox etc.) and serve them via Content-Encoding negotiation when
        # the client supports it. Transparent to the engine (browser decodes
        # before the wasm XHR sees the bytes). Bails to the raw path below for
        # non-compressible exts, Range requests, identity-only clients, or if no
        # encoder is available — so there is no regression. `safe` is the
        # normpath'd archive-relative key (the cache is keyed on it).
        if self._maybe_compressed_asset(full_path, safe, head_only):
            return

        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(size))
        self.send_header("Accept-Ranges", "bytes")
        # Vary so shared/proxy caches don't hand a compressed body (served above
        # for br/gzip clients) to an identity-only client, and vice versa.
        self.send_header("Vary", "Accept-Encoding")
        self.end_headers()
        if not head_only:
            with open(full_path, "rb") as f:
                while True:
                    chunk = f.read(65536)
                    if not chunk:
                        break
                    self.wfile.write(chunk)

    def _serve_range(self, full_path, total_size, range_hdr, content_type="application/octet-stream"):
        try:
            ranges = range_hdr.replace("bytes=", "")
            start_str, end_str = ranges.split("-")
            start = int(start_str) if start_str else 0
            end = int(end_str) if end_str else total_size - 1
        except (ValueError, IndexError):
            self._json_error(416, "Invalid range")
            return

        if start >= total_size:
            self._json_error(416, "Range not satisfiable")
            return

        end = min(end, total_size - 1)
        length = end - start + 1

        self.send_response(206)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(length))
        self.send_header("Content-Range", f"bytes {start}-{end}/{total_size}")
        self.send_header("Accept-Ranges", "bytes")
        self.end_headers()
        with open(full_path, "rb") as f:
            f.seek(start)
            remaining = length
            while remaining > 0:
                chunk = f.read(min(65536, remaining))
                if not chunk:
                    break
                self.wfile.write(chunk)
                remaining -= len(chunk)

    def _json_error(self, code, msg):
        body = json.dumps({"error": msg}).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format, *args):
        # Quieter logging: skip 200s for static assets
        if len(args) >= 2 and str(args[1]) == "200" and not str(args[0]).startswith("GET /api"):
            return
        super().log_message(format, *args)


def _find_assets_dir():
    """Auto-detect extracted assets directory."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(script_dir, "../../orig-assets/extracted"),
        os.path.join(script_dir, "../../../orig-assets/extracted"),
    ]
    env = os.environ.get("RB3_ASSETS")
    if env:
        candidates.insert(0, env)
    for c in candidates:
        if os.path.isdir(c):
            return os.path.realpath(c)
    return None


def _find_fallback_dirs():
    """Auto-detect fallback asset directories (W7-V4 album art etc.).

    The full xbox extraction has per-song _keep.png_xbox cover art that the
    curated default `extracted/` dir strips. We probe it as a secondary root
    so song_select can render real album art without disturbing the primary
    dataset used by smoke tests."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(script_dir, "../../orig-assets/extracted-xbox-full"),
        os.path.join(script_dir, "../../../orig-assets/extracted-xbox-full"),
    ]
    env = os.environ.get("RB3_ASSETS_FALLBACK")
    if env:
        for p in env.split(os.pathsep):
            if p:
                candidates.insert(0, p)
    found = []
    seen = set()
    for c in candidates:
        if os.path.isdir(c):
            real = os.path.realpath(c)
            if real not in seen:
                seen.add(real)
                found.append(real)
    return found


def _find_overlay_dir():
    """Auto-detect the DTA overlay directory (native/dta/).

    The overlay holds small git-tracked DTA patches (e.g. config/joypad.dta
    with its button_meanings block) that shadow the extracted originals. The
    server prefers overlay copies in /api/bundle and /api/file. Overridable via
    RB3_DTA_OVERLAY; returns None gracefully if absent (no overlay = plain
    extracted assets, identical to pre-overlay behavior)."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        # server.py lives at native/web/, so the overlay is one dir up: native/dta
        os.path.join(script_dir, "..", "dta"),
        os.path.join(script_dir, "../../native/dta"),
    ]
    env = os.environ.get("RB3_DTA_OVERLAY")
    if env:
        candidates.insert(0, env)
    for c in candidates:
        if os.path.isdir(c):
            return os.path.realpath(c)
    return None


def _find_downscale_dir():
    """Auto-detect the A4 web-downscaled venue tree (orig-assets/web-downscaled/).

    Generated by scripts/web/gen_web_downscaled.py (gitignored build output, NOT
    the canonical extracted tree). Overridable via RB3_WEB_DOWNSCALE_DIR; returns
    None gracefully if absent (then the downscale is a no-op even when enabled —
    every request falls through to extracted/, no regression)."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(script_dir, "../../orig-assets/web-downscaled"),
        os.path.join(script_dir, "../../../orig-assets/web-downscaled"),
    ]
    env = os.environ.get("RB3_WEB_DOWNSCALE_DIR")
    if env:
        candidates.insert(0, env)
    for c in candidates:
        if os.path.isdir(c):
            return os.path.realpath(c)
    return None


def _downscale_enabled_from_env():
    """RB3_WEB_DOWNSCALE truthiness. Default ON for web (A4 SHIP-DEFAULT —
    visual gate passed pass-with-exclusions, code review clean). Opt out with
    RB3_WEB_DOWNSCALE=0 (or false/off/no). The CLI --downscale / --no-downscale
    override this in main(). When the var is unset we default ON; the stripped
    tree is gitignored build output, so if it's absent _find_downscale_dir()
    returns None and the resolve is a graceful no-op (falls through to
    extracted/, no regression)."""
    v = (os.environ.get("RB3_WEB_DOWNSCALE") or "").strip().lower()
    if v == "":
        return True  # default-ON for web (A4 ship default)
    return v in ("1", "true", "on", "yes")


def _find_sidecar_dir():
    """Auto-detect the offline XMA->PCM sidecar directory (web-xma).

    The 180MB content-hash sidecars live in the gitignored derived tree
    (regenerated by scripts/assets/convert_xma_banks.sh). We serve them on
    demand rather than copying them into the asset set. Overridable via
    RB3_SFX_PCM_DIR; returns None gracefully if absent (then sidecar requests
    just 404, same as before the feature)."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(script_dir, "../../orig-assets/derived/sfx_pcm"),
        os.path.join(script_dir, "../../../orig-assets/derived/sfx_pcm"),
    ]
    env = os.environ.get("RB3_SFX_PCM_DIR")
    if env:
        candidates.insert(0, env)
    for c in candidates:
        if os.path.isdir(c):
            return os.path.realpath(c)
    return None


def _default_encode_cache_dir():
    """Default on-demand compression cache dir: native/web/.cache/encoded/.

    Gitignored derived state (like orig-assets/derived/); a fresh checkout
    starts cold and warms itself. Overridable via RB3_ENCODE_CACHE or
    --encode-cache. Returns the path (not created here — made on first use)."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    env = os.environ.get("RB3_ENCODE_CACHE")
    if env:
        return os.path.abspath(env)
    return os.path.join(script_dir, ".cache", "encoded")


def _spawn_prewarm():
    """Spawn scripts/web/prewarm_encode_cache.py nice-d in the background, passing
    the server's resolved roots + encode cache so the warmed artifacts land under
    the exact dir the server reads. Best-effort: a failed spawn is logged and the
    server still starts (on-demand q5 covers everything)."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    prewarm_py = os.path.join(script_dir, "..", "..", "scripts", "web",
                              "prewarm_encode_cache.py")
    prewarm_py = os.path.normpath(prewarm_py)
    if not os.path.isfile(prewarm_py):
        print(f"  Prewarm: SKIPPED (script not found: {prewarm_py})")
        return
    roots = []
    # A4: when the downscale is on, the stripped tree goes FIRST so its venue
    # milos win the prewarm's first-root-wins de-dupe (same cache key as the
    # extracted milo, but the smaller stripped bytes) — the warmed q11 artifact
    # the server serves is then the stripped+q11 size. Off ⇒ not prepended.
    if DOWNSCALE_ENABLED and DOWNSCALE_DIR:
        roots.append(DOWNSCALE_DIR)
    if ASSETS_DIR:
        roots.append(ASSETS_DIR)
    roots.extend(FALLBACK_ASSETS_DIRS)
    if SIDECAR_DIR:
        roots.append(SIDECAR_DIR)
    cmd = ["nice", "-n", "19", sys.executable, prewarm_py,
           "--encode-cache", ENCODE_CACHE_DIR]
    for r in roots:
        cmd += ["--roots", r]
    log_path = os.path.join(ENCODE_CACHE_DIR, "prewarm.log")
    try:
        os.makedirs(ENCODE_CACHE_DIR, exist_ok=True)
        log_fh = open(log_path, "ab")
        subprocess.Popen(cmd, stdout=log_fh, stderr=subprocess.STDOUT,
                         close_fds=True)
        print(f"  Prewarm: q11 cache warming in background (log: {log_path})")
    except OSError as e:
        print(f"  Prewarm: FAILED to spawn ({e}); on-demand q5 still active")


def main():
    global ASSETS_DIR, FALLBACK_ASSETS_DIRS, SIDECAR_DIR, OVERLAY_DIR
    global ENCODE_CACHE_DIR, ENCODE_ENABLED, ENCODE_LEVEL_BROTLI
    global BROTLI_BIN, GZIP_BIN
    global DOWNSCALE_DIR, DOWNSCALE_ENABLED

    parser = argparse.ArgumentParser(description="RB3 Web Dev Server")
    parser.add_argument(
        "--assets-dir",
        default=None,
        help="Path to extracted game assets (default: RB3_ASSETS env or auto-detect)",
    )
    parser.add_argument(
        "--assets-fallback",
        action="append",
        default=None,
        help=(
            "Additional asset directory probed when a file is missing from "
            "--assets-dir (repeatable; default: RB3_ASSETS_FALLBACK env or "
            "orig-assets/extracted-xbox-full for album art / long-tail assets)."
        ),
    )
    parser.add_argument(
        "--sidecar-dir",
        default=None,
        help=(
            "Directory of offline XMA->PCM sidecars served on demand for the web "
            "build (default: RB3_SFX_PCM_DIR env or "
            "orig-assets/derived/sfx_pcm). Served at /api/file/sfx/gen/xma_pcm/."
        ),
    )
    parser.add_argument(
        "--overlay-dir",
        default=None,
        help=(
            "DTA overlay directory whose files shadow the extracted assets in "
            "/api/bundle and /api/file (default: RB3_DTA_OVERLAY env or "
            "native/dta). Holds small git-tracked DTA patches (e.g. "
            "config/joypad.dta button_meanings)."
        ),
    )
    parser.add_argument(
        "--downscale-dir",
        default=None,
        help=(
            "A4 web-downscaled venue milo tree whose stripped milos shadow the "
            "extracted originals in /api/file when --downscale is on (default: "
            "RB3_WEB_DOWNSCALE_DIR env or orig-assets/web-downscaled). Generated "
            "by scripts/web/gen_web_downscaled.py."
        ),
    )
    parser.add_argument(
        "--downscale",
        dest="downscale",
        action="store_true",
        default=None,
        help=(
            "Enable the A4 web texture downscale: serve mip-stripped venue milos "
            "from the downscaled tree (default OFF; also RB3_WEB_DOWNSCALE=1). The "
            "prewarm walks the downscaled tree so the warmed wire is stripped+q11."
        ),
    )
    parser.add_argument(
        "--no-downscale",
        dest="downscale",
        action="store_false",
        help="Force the A4 web downscale OFF (overrides RB3_WEB_DOWNSCALE env).",
    )
    parser.add_argument(
        "--encode-cache",
        default=None,
        help=(
            "Cache dir for on-demand-compressed assets (R5 wire compression; "
            "default: RB3_ENCODE_CACHE env or native/web/.cache/encoded). "
            ".milo_xbox etc. are brotli/gzip-compressed once and served via "
            "Content-Encoding negotiation."
        ),
    )
    parser.add_argument(
        "--encode-level",
        type=int,
        default=None,
        help=(
            "brotli quality for on-demand compression (default 5 — keeps ~90%% "
            "of q11's win at ~1/100th the CPU, paid inline on the first fetch)."
        ),
    )
    parser.add_argument(
        "--no-encode",
        action="store_true",
        help="Disable on-demand wire compression (serve assets raw; for A/B).",
    )
    parser.add_argument(
        "--prewarm",
        action="store_true",
        help=(
            "On startup, spawn scripts/web/prewarm_encode_cache.py nice-d in the "
            "background to pre-build the q11 encode cache (assets + bundles). The "
            "server starts serving immediately; on-demand q5 covers anything not "
            "yet warm. The script is also runnable standalone."
        ),
    )
    parser.add_argument("--port", type=int, default=PORT)
    args = parser.parse_args()

    ASSETS_DIR = args.assets_dir or _find_assets_dir()
    OVERLAY_DIR = (
        os.path.realpath(args.overlay_dir)
        if args.overlay_dir and os.path.isdir(args.overlay_dir)
        else _find_overlay_dir()
    )
    if args.assets_fallback:
        FALLBACK_ASSETS_DIRS = [
            os.path.realpath(p) for p in args.assets_fallback if os.path.isdir(p)
        ]
    else:
        FALLBACK_ASSETS_DIRS = _find_fallback_dirs()
    SIDECAR_DIR = (
        os.path.realpath(args.sidecar_dir)
        if args.sidecar_dir and os.path.isdir(args.sidecar_dir)
        else _find_sidecar_dir()
    )

    # A4 web texture downscale: resolve the tree + the enable flag. CLI
    # --downscale/--no-downscale (args.downscale True/False) overrides the
    # RB3_WEB_DOWNSCALE env; default OFF when neither is given.
    DOWNSCALE_DIR = (
        os.path.realpath(args.downscale_dir)
        if args.downscale_dir and os.path.isdir(args.downscale_dir)
        else _find_downscale_dir()
    )
    if args.downscale is not None:
        DOWNSCALE_ENABLED = args.downscale
    else:
        DOWNSCALE_ENABLED = _downscale_enabled_from_env()

    # R5 — on-demand wire compression config + encoder probe.
    ENCODE_ENABLED = not args.no_encode
    ENCODE_CACHE_DIR = (
        os.path.abspath(args.encode_cache)
        if args.encode_cache
        else _default_encode_cache_dir()
    )
    if args.encode_level is not None:
        ENCODE_LEVEL_BROTLI = args.encode_level
    # Probe the encoder binaries once. brotli (primary) reuses build.sh's exact
    # CLI; gzip (CLI) is the always-available fallback. Python `brotli` module is
    # absent on this machine, so the CLI is the only brotli path. If neither
    # brotli is found we degrade to gzip-only (mirrors build.sh's fallback).
    BROTLI_BIN = shutil.which("brotli")
    GZIP_BIN = shutil.which("gzip")
    if ENCODE_ENABLED and not (BROTLI_BIN or GZIP_BIN):
        ENCODE_ENABLED = False  # no encoder → raw path everywhere

    if not os.path.isdir(BUILD_DIR):
        print(f"Build directory not found: {BUILD_DIR}")
        print("Run scripts/web/build.sh first.")
        sys.exit(1)

    print("RB3 Web Dev Server")
    print(f"  Build:   {BUILD_DIR}")
    if ASSETS_DIR:
        print(f"  Assets:  {ASSETS_DIR}")
    else:
        print("  Assets:  NOT CONFIGURED (set --assets-dir or RB3_ASSETS)")
    if FALLBACK_ASSETS_DIRS:
        for fb in FALLBACK_ASSETS_DIRS:
            print(f"  Fallback: {fb}")
    if OVERLAY_DIR:
        print(f"  Overlay: {OVERLAY_DIR} (DTA overlay; shadows extracted assets)")
    if SIDECAR_DIR:
        print(f"  Sidecars: {SIDECAR_DIR} (XMA->PCM, served on demand)")
    if DOWNSCALE_ENABLED:
        if DOWNSCALE_DIR:
            print(f"  Downscale: ON  {DOWNSCALE_DIR} (A4 mip-stripped venue milos "
                  f"shadow extracted/)")
        else:
            print("  Downscale: ON but tree NOT FOUND (RB3_WEB_DOWNSCALE_DIR / "
                  "orig-assets/web-downscaled) — falling through to extracted/ "
                  "(run scripts/web/gen_web_downscaled.py)")
    else:
        print("  Downscale: off (A4 default-ON; opt-out via RB3_WEB_DOWNSCALE=0 "
              "or --no-downscale)")
    if not ENCODE_ENABLED:
        print("  Encode:  DISABLED (assets served raw)")
    elif BROTLI_BIN:
        print(
            f"  Encode:  brotli q{ENCODE_LEVEL_BROTLI} (CLI {BROTLI_BIN})"
            f" + gzip fallback -> {ENCODE_CACHE_DIR}"
        )
    else:
        print(
            f"  Encode:  gzip-only -{ENCODE_LEVEL_GZIP} (brotli CLI NOT found)"
            f" -> {ENCODE_CACHE_DIR}"
        )
    print(f"  URL:     http://0.0.0.0:{args.port} (accessible remotely)")
    print(f"  API:     http://0.0.0.0:{args.port}/api/manifest")
    print(f"  COOP/COEP headers enabled")

    if args.prewarm:
        _spawn_prewarm()
    print()

    server = http.server.ThreadingHTTPServer(("0.0.0.0", args.port), RB3Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()


if __name__ == "__main__":
    main()
