#!/usr/bin/env python3
"""Generate native/src/band3_link_stubs.s (+ band3_stub_table.inc) from the
registry native/src/band3_stub_registry.tsv.

The registry TSV is the source of truth for the weak-symbol link stubs that
paper over the ~43 band3/system TUs excluded from the rb3-native clang LP64
build (see native/CMakeLists.txt _NATIVE_FORK_EXCLUDE). Each registry row
classifies one weak symbol as:

    kind  ∈ func | data
    class ∈ assert-unreachable | ok-noop | data-blob

Two emission modes:

  --mode loud   (W0.2.S2, DEFAULT): each `func` row becomes a per-symbol
                logging trampoline `__hmx_tramp_<i>` — a cheap already-hit
                fast path (cmpb/jne/xor/ret) plus a first-hit call to the
                extern "C" census hook `__hmx_stub_first_hit(name)`. A parallel
                C++ table `band3_stub_table.inc` (one HmxStubInfo row per
                symbol + the three count constants) is emitted for the census
                / gtest to consume. `data` rows keep their own writable `.bss`
                `.zero <N>` reservation. Returning 0 for every func stub is
                behavior-identical to the old shared no-op, so a *called* stub
                cannot regress; the trampoline only ADDS the loud first-hit log.

  --mode legacy (W0.2.S1): every `func` row (regardless of class) aliases to a
                single shared `__hmx_band3_noop_stub` (xorl %eax,%eax; ret); no
                trampolines, no census, no `.inc`. Kept for reference / A-B.

Usage:
    python3 scripts/native/gen_band3_link_stubs.py            # loud (default)
    python3 scripts/native/gen_band3_link_stubs.py --check    # drift gate (loud)
    python3 scripts/native/gen_band3_link_stubs.py --mode legacy

Running with no registry change must leave the tree clean (idempotent) — this
is the drift gate `stub_census_smoke.py --check-sync` builds on later.
"""
import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REGISTRY = REPO_ROOT / "native/src/band3_stub_registry.tsv"
DEFAULT_OUTPUT = REPO_ROOT / "native/src/band3_link_stubs.s"
DEFAULT_TABLE = REPO_ROOT / "native/src/band3_stub_table.inc"

VALID_KINDS = {"func", "data"}
VALID_CLASSES = {"assert-unreachable", "ok-noop", "data-blob"}

# class -> single-char code used in band3_stub_table.inc
CLS_CODE = {"assert-unreachable": "A", "ok-noop": "N", "data-blob": "D"}

HEADER_COMMON = """\
// AUTO-GENERATED by scripts/native/gen_band3_link_stubs.py from
// native/src/band3_stub_registry.tsv — DO NOT HAND-EDIT. Edit the registry
// (and re-run the generator) instead.
//
// weak no-op stubs for the boot-path link symbols defined by the
// ~43 band3/{meta_band,game,tour,net_band,bandtrack} + system/{bandobj,char,
// beatmatch,meta,movie} matched-fork TUs that do NOT yet compile under clang
// LP64 (see native/CMakeLists.txt _NATIVE_FORK_EXCLUDE). Those TUs are excluded
// from the rb3-native link; the boot spine (App.cpp) + the compiled boot-path
// TUs still REFERENCE symbols those excluded TUs would define (BandInit,
// MetaPanel::Init, manager singletons/vtables/typeinfo, static members, …).
// Each name is WEAK -> any real definition wins; the rest resolve to a stub.
// Splits FUNCTION stubs from DATA stubs (each gets its own writable .bss
// reservation; safe to read AND write — singletons/globals/static members/
// vtables/typeinfo). None is on the matched-fork asm-match line.
//
// The classification (assert-unreachable | ok-noop | data-blob) and any
// per-symbol justification live in band3_stub_registry.tsv; historical
// "REMOVED — now strongly defined" notes for symbols that graduated out of
// this file live in its git history, not here.
"""

HEADER_LEGACY = HEADER_COMMON + """\
//
// MODE: legacy — every FUNCTION stub aliases the single shared
// __hmx_band3_noop_stub (xorl %eax,%eax; ret). No census.
//
// Regenerate: edit native/src/band3_stub_registry.tsv, then run
//   python3 scripts/native/gen_band3_link_stubs.py --mode legacy
"""

HEADER_LOUD = HEADER_COMMON + """\
//
// MODE: loud (default) — each FUNCTION stub is a per-symbol trampoline
// __hmx_tramp_<i> that logs its FIRST call to stderr (via the extern "C"
// census hook __hmx_stub_first_hit) and records the hit for a startup+atexit
// census (rb3_stub_census.cpp), then falls through to the legacy behavior of
// returning 0. The already-hit fast path is cmpb/jne/xor/ret (≤4 insns), so a
// hot stub is ~free. Returning 0 is behavior-identical to the old shared
// no-op; the trampoline only ADDS the loud first-hit signal so an invisible
// swallowed call (à la DrawParticlesBillboard / EndGame) surfaces on frame 1.
//
// A parallel C++ table is emitted as band3_stub_table.inc (kept in sync by
// this generator — do not hand-edit either). rb3-native links PIE, so the
// trampoline uses RIP-relative addressing + call ...@PLT.
//
// Regenerate: edit native/src/band3_stub_registry.tsv, then run
//   python3 scripts/native/gen_band3_link_stubs.py
"""

TABLE_HEADER = """\
// AUTO-GENERATED by scripts/native/gen_band3_link_stubs.py from
// native/src/band3_stub_registry.tsv — DO NOT HAND-EDIT.
//
// C++ census table paired with the __hmx_tramp_<i> trampolines in
// band3_link_stubs.s (loud mode). Consumed by rb3_stub_census.cpp and the
// stub-census gtest. `kind`: 'F'=func, 'D'=data. `cls`: 'A'=assert-unreachable,
// 'N'=ok-noop, 'D'=data-blob.
struct HmxStubInfo { const char* name; char kind; char cls; };

static const HmxStubInfo kHmxStubTable[] = {
"""


def parse_registry(path: Path):
    rows = []
    seen = set()
    with open(path, "r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 4:
                sys.exit(f"{path}:{lineno}: expected 4 tab-separated fields, got {len(parts)}: {line!r}")
            symbol, kind, cls, note = parts
            if kind not in VALID_KINDS:
                sys.exit(f"{path}:{lineno}: invalid kind {kind!r} for {symbol}")
            if kind == "data" and cls != "data-blob":
                sys.exit(f"{path}:{lineno}: data row {symbol} must have class=data-blob, got {cls!r}")
            if kind == "func" and cls not in ("assert-unreachable", "ok-noop"):
                sys.exit(f"{path}:{lineno}: func row {symbol} must have class in "
                          f"{{assert-unreachable, ok-noop}}, got {cls!r}")
            if symbol in seen:
                sys.exit(f"{path}:{lineno}: duplicate symbol {symbol}")
            seen.add(symbol)
            rows.append({"symbol": symbol, "kind": kind, "class": cls, "note": note})
    return rows


def bss_size(row) -> int:
    for tok in row["note"].split(";"):
        tok = tok.strip()
        if tok.startswith("bss="):
            return int(tok[len("bss="):])
    sys.exit(f"data row {row['symbol']} is missing a bss=<N> note")


def emit_legacy(rows):
    funcs = sorted((r for r in rows if r["kind"] == "func"), key=lambda r: r["symbol"])
    datas = sorted((r for r in rows if r["kind"] == "data"), key=lambda r: r["symbol"])

    out = [HEADER_LEGACY]
    out.append("    .text\n")
    out.append("    .p2align 4\n")
    out.append("__hmx_band3_noop_stub:\n")
    out.append("    xorl %eax, %eax\n")
    out.append("    ret\n")
    out.append("\n")
    out.append("    // ---- FUNCTION stubs (call -> harmless no-op returning 0) ----\n")
    for r in funcs:
        sym = r["symbol"]
        out.append(f"    .weak {sym}\n")
        out.append(f"    .set {sym}, __hmx_band3_noop_stub\n")
    out.append("\n")
    out.append("    // ---- DATA stubs (each: own writable zero-filled reservation) ----\n")
    out.append("    .bss\n")
    out.append("    .p2align 4\n")
    for r in datas:
        sym = r["symbol"]
        size = bss_size(r)
        out.append(f"    .weak {sym}\n")
        out.append(f"{sym}:\n")
        out.append(f"    .zero {size}\n")
    return "".join(out)


def emit_loud(rows):
    """Returns (asm_text, inc_text).

    func rows are emitted in a stable order (registry order preserved — the
    registry itself is alphabetical from S1), each getting a numeric index i so
    the trampoline/name/latch labels (__hmx_tramp_<i> / __hmx_name_<i> /
    __hmx_latch_<i>) are always valid + unique regardless of the mangled symbol
    text. The real symbol name lives only in the .asciz string + the .weak/.set
    directives.
    """
    funcs = sorted((r for r in rows if r["kind"] == "func"), key=lambda r: r["symbol"])
    datas = sorted((r for r in rows if r["kind"] == "data"), key=lambda r: r["symbol"])

    # ---- asm ----
    a = [HEADER_LOUD]

    # Trampolines (.text). Each: already-hit fast path (cmpb/jne/xor/ret) +
    # first-hit call to __hmx_stub_first_hit@PLT (PIE-safe: @PLT + RIP-relative).
    a.append("    .text\n")
    a.append("    // ---- FUNCTION stubs: per-symbol loud first-hit trampolines ----\n")
    for i, r in enumerate(funcs):
        sym = r["symbol"]
        a.append("    .p2align 4\n")
        a.append(f"__hmx_tramp_{i}:\n")
        a.append(f"    cmpb $0, __hmx_latch_{i}(%rip)\n")
        a.append(f"    jne 1f\n")
        a.append(f"    movb $1, __hmx_latch_{i}(%rip)\n")
        a.append(f"    leaq __hmx_name_{i}(%rip), %rdi\n")
        a.append(f"    call __hmx_stub_first_hit@PLT\n")
        a.append("1:  xorl %eax, %eax\n")
        a.append("    ret\n")
        a.append(f"    .weak {sym}\n")
        a.append(f"    .set {sym}, __hmx_tramp_{i}\n")

    # Name strings (.rodata).
    a.append("\n")
    a.append("    .section .rodata\n")
    for i, r in enumerate(funcs):
        a.append(f"__hmx_name_{i}:\n")
        a.append(f"    .asciz \"{r['symbol']}\"\n")

    # Latches (.bss, 1 byte each).
    a.append("\n")
    a.append("    .bss\n")
    a.append("    // ---- per-symbol first-hit latches (1 byte each) ----\n")
    for i, r in enumerate(funcs):
        a.append(f"__hmx_latch_{i}:\n")
        a.append("    .zero 1\n")

    # DATA stubs (.bss, own writable reservation — unchanged shape from legacy).
    a.append("\n")
    a.append("    // ---- DATA stubs (each: own writable zero-filled reservation) ----\n")
    a.append("    .p2align 4\n")
    for r in datas:
        sym = r["symbol"]
        size = bss_size(r)
        a.append(f"    .weak {sym}\n")
        a.append(f"{sym}:\n")
        a.append(f"    .zero {size}\n")

    # ---- C++ table (.inc) ----
    t = [TABLE_HEADER]
    for r in funcs:
        t.append(f"    {{ \"{r['symbol']}\", 'F', '{CLS_CODE[r['class']]}' }},\n")
    for r in datas:
        t.append(f"    {{ \"{r['symbol']}\", 'D', 'D' }},\n")
    t.append("};\n")
    t.append("\n")
    t.append(f"static const int kHmxStubTotal = {len(funcs) + len(datas)};\n")
    t.append(f"static const int kHmxStubFunc  = {len(funcs)};\n")
    t.append(f"static const int kHmxStubData  = {len(datas)};\n")

    return "".join(a), "".join(t)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=["loud", "legacy"], default="loud",
                     help="emission mode: 'loud' (default, per-symbol census trampolines) "
                          "or 'legacy' (single shared no-op, no census)")
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    ap.add_argument("--table-output", type=Path, default=DEFAULT_TABLE,
                     help="C++ census table path (loud mode only)")
    ap.add_argument("--check", action="store_true",
                     help="don't write; exit 1 if generated output differs from what's on disk "
                          "(idempotency / drift gate)")
    args = ap.parse_args()

    rows = parse_registry(args.registry)

    func_rows = [r for r in rows if r["kind"] == "func"]
    data_rows = [r for r in rows if r["kind"] == "data"]
    print(f"registry: {len(rows)} symbols ({len(func_rows)} func / {len(data_rows)} data)", file=sys.stderr)

    if args.mode == "legacy":
        asm_content = emit_legacy(rows)
        table_content = None
    else:
        asm_content, table_content = emit_loud(rows)

    if args.check:
        rc = 0
        if not args.output.exists():
            print(f"MISSING: {args.output}", file=sys.stderr)
            rc = 1
        elif args.output.read_text(encoding="utf-8") != asm_content:
            print(f"DRIFT: {args.output} does not match registry-generated output", file=sys.stderr)
            rc = 1
        if table_content is not None:
            if not args.table_output.exists():
                print(f"MISSING: {args.table_output}", file=sys.stderr)
                rc = 1
            elif args.table_output.read_text(encoding="utf-8") != table_content:
                print(f"DRIFT: {args.table_output} does not match registry-generated output", file=sys.stderr)
                rc = 1
        if rc == 0:
            print("OK: no drift", file=sys.stderr)
        return rc

    args.output.write_text(asm_content, encoding="utf-8")
    print(f"wrote {args.output}", file=sys.stderr)
    if table_content is not None:
        args.table_output.write_text(table_content, encoding="utf-8")
        print(f"wrote {args.table_output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
