#!/usr/bin/env python3
"""Generate native/src/band3_link_stubs.s from native/src/band3_stub_registry.tsv.

The registry TSV is the source of truth for the weak-symbol link stubs that
paper over the ~43 band3/system TUs excluded from the rb3-native clang LP64
build (see native/CMakeLists.txt _NATIVE_FORK_EXCLUDE). Each registry row
classifies one weak symbol as:

    kind  ∈ func | data
    class ∈ assert-unreachable | ok-noop | data-blob

W0.2.S1 scope: this script only supports `--mode legacy`, which emits the
*current* file shape — every `func` row (regardless of class) aliases to the
single shared `__hmx_band3_noop_stub` (xorl %eax,%eax; ret), and every `data`
row gets its own writable `.bss` `.zero <N>` reservation. No trampolines, no
census hooks — behavior-identical to the hand-written file this replaces.
(The loud per-symbol trampoline emission lands in W0.2.S2 as a new mode.)

Usage:
    python3 scripts/native/gen_band3_link_stubs.py --mode legacy
    python3 scripts/native/gen_band3_link_stubs.py --mode legacy --check   # idempotency/drift gate

Running with no registry change must leave the tree clean (idempotent) —
this is the drift gate `stub_census_smoke.py --check-sync` builds on later.
"""
import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REGISTRY = REPO_ROOT / "native/src/band3_stub_registry.tsv"
DEFAULT_OUTPUT = REPO_ROOT / "native/src/band3_link_stubs.s"

VALID_KINDS = {"func", "data"}
VALID_CLASSES = {"assert-unreachable", "ok-noop", "data-blob"}

HEADER = """\
// AUTO-GENERATED by scripts/native/gen_band3_link_stubs.py from
// native/src/band3_stub_registry.tsv — DO NOT HAND-EDIT. Edit the registry
// (and re-run the generator) instead.
//
// weak no-op stubs for the boot-path link symbols defined by the
// ~43 band3/{meta_band,game,tour,net_band,bandtrack} + system/{bandobj,char,
// beatmatch,meta,movie} matched-fork TUs that do NOT yet compile under clang
// LP64 (see native/CMakeLists.txt _NATIVE_FORK_EXCLUDE). Those TUs are excluded
// from the rb3-native link; the boot spine (App.cpp) + the compiled boot-path
// TUs still REFERENCE symbols those excluded TUs would define (BandInit,
// MetaPanel::Init, manager singletons/vtables/typeinfo, static members, …).
// Each name is WEAK -> any real definition wins; the rest resolve to a shared
// no-op. Splits FUNCTION stubs (point at a .text noop; safe to call) from
// DATA stubs (each gets its own writable .bss reservation; safe to read AND
// write — singletons/globals/static members/vtables/typeinfo). None is on
// the matched-fork asm-match line.
//
// The classification (assert-unreachable | ok-noop | data-blob) and any
// per-symbol justification live in band3_stub_registry.tsv; historical
// "REMOVED — now strongly defined" notes for symbols that graduated out of
// this file live in its git history, not here.
//
// Regenerate: edit native/src/band3_stub_registry.tsv, then run
//   python3 scripts/native/gen_band3_link_stubs.py --mode legacy
"""


def parse_registry(path: Path):
    rows = []
    seen = set()
    with open(path, "r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 4:
                sys.exit(f"{path}:{lineno}: expected 4 tab-separated fields, got {len(parts)}: {line!r}")
            symbol, kind, cls, note = parts
            if kind not in VALID_KINDS:
                sys.exit(f"{path}:{lineno}: invalid kind {kind!r} for {symbol}")
            if kind == "data" and cls != "data-blob":
                sys.exit(f"{path}:{lineno}: data row {symbol} must have class=data-blob, got {cls!r}")
            if kind == "func" and cls not in ("assert-unreachable", "ok-noop"):
                sys.exit(f"{path}:{lineno}: func row {symbol} must have class in "
                          f"{{assert-unreachable, ok-noop}}, got {cls!r}")
            if symbol in seen:
                sys.exit(f"{path}:{lineno}: duplicate symbol {symbol}")
            seen.add(symbol)
            rows.append({"symbol": symbol, "kind": kind, "class": cls, "note": note})
    return rows


def bss_size(row) -> int:
    for tok in row["note"].split(";"):
        tok = tok.strip()
        if tok.startswith("bss="):
            return int(tok[len("bss="):])
    sys.exit(f"data row {row['symbol']} is missing a bss=<N> note")


def emit_legacy(rows):
    funcs = sorted((r for r in rows if r["kind"] == "func"), key=lambda r: r["symbol"])
    datas = sorted((r for r in rows if r["kind"] == "data"), key=lambda r: r["symbol"])

    out = [HEADER]
    out.append("    .text\n")
    out.append("    .p2align 4\n")
    out.append("__hmx_band3_noop_stub:\n")
    out.append("    xorl %eax, %eax\n")
    out.append("    ret\n")
    out.append("\n")
    out.append("    // ---- FUNCTION stubs (call -> harmless no-op returning 0) ----\n")
    for r in funcs:
        sym = r["symbol"]
        out.append(f"    .weak {sym}\n")
        out.append(f"    .set {sym}, __hmx_band3_noop_stub\n")
    out.append("\n")
    out.append("    // ---- DATA stubs (each: own writable zero-filled reservation) ----\n")
    out.append("    .bss\n")
    out.append("    .p2align 4\n")
    for r in datas:
        sym = r["symbol"]
        size = bss_size(r)
        out.append(f"    .weak {sym}\n")
        out.append(f"{sym}:\n")
        out.append(f"    .zero {size}\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=["legacy"], default="legacy",
                     help="emission mode (only 'legacy' — current shared-no-op shape — exists so far)")
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    ap.add_argument("--check", action="store_true",
                     help="don't write; exit 1 if generated output differs from --output on disk "
                          "(idempotency / drift gate)")
    args = ap.parse_args()

    rows = parse_registry(args.registry)

    func_rows = [r for r in rows if r["kind"] == "func"]
    data_rows = [r for r in rows if r["kind"] == "data"]
    print(f"registry: {len(rows)} symbols ({len(func_rows)} func / {len(data_rows)} data)", file=sys.stderr)

    if args.mode == "legacy":
        content = emit_legacy(rows)
    else:
        sys.exit(f"unknown mode {args.mode}")

    if args.check:
        if not args.output.exists():
            print(f"MISSING: {args.output}", file=sys.stderr)
            return 1
        current = args.output.read_text(encoding="utf-8")
        if current != content:
            print(f"DRIFT: {args.output} does not match registry-generated output", file=sys.stderr)
            return 1
        print("OK: no drift", file=sys.stderr)
        return 0

    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
