#include "types.h"
s32 bta_dm_enable(void) { return 0; }
s32 bta_dm_disable(void) { return 0; }
s32 bta_dm_disable_timer_cback(void) { return 0; }
s32 bta_dm_set_dev_name(void) { return 0; }
s32 bta_dm_set_visibility(void) { return 0; }
s32 bta_dm_bond(void) { return 0; }
s32 bta_dm_pin_reply(void) { return 0; }
s32 bta_dm_auth_reply(void) { return 0; }
s32 bta_dm_search_start(void) { return 0; }
s32 bta_dm_search_cancel(void) { return 0; }
s32 bta_dm_discover(void) { return 0; }
s32 bta_dm_inq_cmpl(void) { return 0; }
s32 bta_dm_rmt_name(void) { return 0; }
s32 bta_dm_disc_rmt_name(void) { return 0; }
s32 bta_dm_sdp_result(void) { return 0; }
s32 bta_dm_search_cmpl(void) { return 0; }
s32 bta_dm_disc_result(void) { return 0; }
s32 bta_dm_search_result(void) { return 0; }
s32 bta_dm_search_timer_cback(void) { return 0; }
s32 bta_dm_free_sdp_db(void) { return 0; }
s32 bta_dm_queue_search(void) { return 0; }
s32 bta_dm_queue_disc(void) { return 0; }
s32 bta_dm_search_clear_queue(void) { return 0; }
s32 bta_dm_search_cancel_cmpl(void) { return 0; }
s32 bta_dm_search_cancel_transac_cmpl(void) { return 0; }
s32 bta_dm_search_cancel_notify(void) { return 0; }
s32 bta_dm_find_services(void) { return 0; }
s32 bta_dm_discover_next_device(void) { return 0; }
s32 bta_dm_sdp_callback(void) { return 0; }
s32 bta_dm_inq_results_cb(void) { return 0; }
s32 bta_dm_inq_cmpl_cb(void) { return 0; }
s32 bta_dm_service_search_remname_cback(void) { return 0; }
s32 bta_dm_remname_cback(void) { return 0; }
s32 bta_dm_disc_remname_cback(void) { return 0; }
s32 bta_dm_cancel_rmt_name(void) { return 0; }
s32 bta_dm_authorize_cback(void) { return 0; }
s32 bta_dm_pinname_cback(void) { return 0; }
s32 bta_dm_pin_cback(void) { return 0; }
s32 bta_dm_link_key_request_cback(void) { return 0; }
s32 bta_dm_new_link_key_cback(void) { return 0; }
s32 bta_dm_authentication_complete_cback(void) { return 0; }
s32 bta_dm_local_addr_cback(void) { return 0; }
s32 bta_dm_signal_strength(void) { return 0; }
s32 bta_dm_signal_strength_timer_cback(void) { return 0; }
s32 bta_dm_acl_change_cback(void) { return 0; }
s32 bta_dm_acl_change(void) { return 0; }
s32 bta_dm_disable_conn_down_timer_cback(void) { return 0; }
s32 bta_dm_rssi_cback(void) { return 0; }
s32 bta_dm_link_quality_cback(void) { return 0; }
s32 bta_dm_l2cap_server_compress_cback(void) { return 0; }
s32 bta_dm_compress_cback(void) { return 0; }
s32 bta_dm_rm_cback(void) { return 0; }
s32 bta_dm_keep_acl(void) { return 0; }
s32 bta_dm_immediate_disable(void) { return 0; }
s32 bta_dm_reset_complete(void) { return 0; }
s32 bta_dm_send_hci_reset(void) { return 0; }
