#include "types.h"
s32 BTM_SecRegister(void) { return 0; }
s32 BTM_SecAddRmtNameNotifyCallback(void) { return 0; }
s32 BTM_SecDeleteRmtNameNotifyCallback(void) { return 0; }
s32 BTM_SetPinType(void) { return 0; }
s32 BTM_SetSecurityLevel(void) { return 0; }
s32 BTM_PINCodeReply(void) { return 0; }
s32 BTM_DeviceAuthorized(void) { return 0; }
s32 BTM_SecBond(void) { return 0; }
s32 btm_sec_l2cap_access_req(void) { return 0; }
s32 btm_sec_mx_access_request(void) { return 0; }
s32 btm_sec_conn_req(void) { return 0; }
s32 btm_sec_init(void) { return 0; }
s32 btm_sec_dev_reset(void) { return 0; }
s32 btm_sec_abort_access_req(void) { return 0; }
s32 btm_sec_rmt_name_request_complete(void) { return 0; }
s32 btm_sec_auth_complete(void) { return 0; }
s32 btm_sec_mkey_comp_event(void) { return 0; }
s32 btm_sec_encrypt_change(void) { return 0; }
s32 btm_sec_is_bonding(void) { return 0; }
s32 btm_sec_connected(void) { return 0; }
s32 btm_sec_disconnect(void) { return 0; }
s32 btm_sec_disconnected(void) { return 0; }
s32 btm_sec_link_key_notification(void) { return 0; }
s32 btm_sec_link_key_request(void) { return 0; }
s32 btm_sec_pin_code_request_timeout(void) { return 0; }
s32 btm_sec_pin_code_request(void) { return 0; }
s32 btm_sec_update_clock_offset(void) { return 0; }
s32 btm_sec_execute_procedure(void) { return 0; }
s32 btm_sec_start_authorization(void) { return 0; }
s32 btm_sec_collision_timeout(void) { return 0; }
s32 btm_read_trusted_mask(void) { return 0; }
