#include "types.h"
s32 btm_acl_init(void) { return 0; }
s32 btm_handle_to_acl_index(void) { return 0; }
s32 btm_acl_created(void) { return 0; }
s32 btm_acl_removed(void) { return 0; }
s32 btm_acl_device_down(void) { return 0; }
s32 BTM_SwitchRole(void) { return 0; }
s32 btm_acl_encrypt_change(void) { return 0; }
s32 BTM_SetLinkPolicy(void) { return 0; }
s32 BTM_SetDefaultLinkPolicy(void) { return 0; }
s32 btm_read_link_policy_complete(void) { return 0; }
s32 btm_read_remote_version_complete(void) { return 0; }
s32 btm_read_remote_features_complete(void) { return 0; }
s32 BTM_SetDefaultLinkSuperTout(void) { return 0; }
s32 BTM_IsAclConnectionUp(void) { return 0; }
s32 BTM_GetNumAclLinks(void) { return 0; }
s32 btm_get_acl_disc_reason_code(void) { return 0; }
s32 BTM_GetHCIConnHandle(void) { return 0; }
s32 btm_process_clk_off_comp_evt(void) { return 0; }
s32 btm_acl_role_changed(void) { return 0; }
s32 btm_acl_timeout(void) { return 0; }
s32 btm_get_max_packet_size(void) { return 0; }
s32 BTM_AclRegisterForChanges(void) { return 0; }
s32 btm_qos_setup_complete(void) { return 0; }
s32 BTM_ReadRSSI(void) { return 0; }
s32 BTM_ReadLinkQuality(void) { return 0; }
s32 btm_read_rssi_complete(void) { return 0; }
s32 btm_read_link_quality_complete(void) { return 0; }
s32 btm_remove_acl(void) { return 0; }
s32 btm_chg_all_acl_pkt_types(void) { return 0; }
