#include "types.h"
s32 btm_dev_init(void) { return 0; }
s32 btm_db_reset(void) { return 0; }
s32 BTM_DeviceReset(void) { return 0; }
s32 BTM_SendHciReset(void) { return 0; }
s32 BTM_IsDeviceUp(void) { return 0; }
s32 BTM_SetAfhChannels(void) { return 0; }
s32 btm_dev_timeout(void) { return 0; }
s32 btm_reset_complete(void) { return 0; }
s32 btm_read_hci_buf_size_complete(void) { return 0; }
s32 btm_read_local_version_complete(void) { return 0; }
s32 btm_read_local_features_complete(void) { return 0; }
s32 BTM_SetLocalDeviceName(void) { return 0; }
s32 btm_read_local_name_complete(void) { return 0; }
s32 BTM_ReadLocalDeviceAddr(void) { return 0; }
s32 btm_read_local_addr_complete(void) { return 0; }
s32 BTM_ReadLocalVersion(void) { return 0; }
s32 BTM_SetDeviceClass(void) { return 0; }
s32 BTM_ReadDeviceClass(void) { return 0; }
s32 BTM_ReadLocalFeatures(void) { return 0; }
s32 BTM_RegisterForDeviceStatusNotif(void) { return 0; }
s32 BTM_VendorSpecificCommand(void) { return 0; }
s32 btm_vsc_complete(void) { return 0; }
s32 BTM_RegisterForVSEvents(void) { return 0; }
s32 btm_vendor_specific_evt(void) { return 0; }
s32 BTM_WritePageTimeout(void) { return 0; }
s32 BTM_ReadStoredLinkKey(void) { return 0; }
s32 BTM_WriteStoredLinkKey(void) { return 0; }
s32 BTM_DeleteStoredLinkKey(void) { return 0; }
s32 btm_read_stored_link_key_complete(void) { return 0; }
s32 btm_write_stored_link_key_complete(void) { return 0; }
s32 btm_delete_stored_link_key_complete(void) { return 0; }
s32 btm_return_link_keys_evt(void) { return 0; }
s32 btm_report_device_status(void) { return 0; }
