#include "types.h"
s32 btsnd_hcic_inquiry(void) { return 0; }
s32 btsnd_hcic_inq_cancel(void) { return 0; }
s32 btsnd_hcic_per_inq_mode(void) { return 0; }
s32 btsnd_hcic_create_conn(void) { return 0; }
s32 btsnd_hcic_disconnect(void) { return 0; }
s32 btsnd_hcic_add_SCO_conn(void) { return 0; }
s32 btsnd_hcic_accept_conn(void) { return 0; }
s32 btsnd_hcic_reject_conn(void) { return 0; }
s32 btsnd_hcic_link_key_req_reply(void) { return 0; }
s32 btsnd_hcic_link_key_neg_reply(void) { return 0; }
s32 btsnd_hcic_pin_code_req_reply(void) { return 0; }
s32 btsnd_hcic_pin_code_neg_reply(void) { return 0; }
s32 btsnd_hcic_change_conn_type(void) { return 0; }
s32 btsnd_hcic_auth_request(void) { return 0; }
s32 btsnd_hcic_set_conn_encrypt(void) { return 0; }
s32 btsnd_hcic_rmt_name_req(void) { return 0; }
s32 btsnd_hcic_rmt_name_req_cancel(void) { return 0; }
s32 btsnd_hcic_rmt_features_req(void) { return 0; }
s32 btsnd_hcic_rmt_ver_req(void) { return 0; }
s32 btsnd_hcic_read_rmt_clk_offset(void) { return 0; }
s32 btsnd_hcic_setup_esco_conn(void) { return 0; }
s32 btsnd_hcic_accept_esco_conn(void) { return 0; }
s32 btsnd_hcic_reject_esco_conn(void) { return 0; }
s32 btsnd_hcic_hold_mode(void) { return 0; }
s32 btsnd_hcic_sniff_mode(void) { return 0; }
s32 btsnd_hcic_exit_sniff_mode(void) { return 0; }
s32 btsnd_hcic_park_mode(void) { return 0; }
s32 btsnd_hcic_exit_park_mode(void) { return 0; }
s32 btsnd_hcic_switch_role(void) { return 0; }
s32 btsnd_hcic_write_policy_set(void) { return 0; }
s32 btsnd_hcic_reset(void) { return 0; }
s32 btsnd_hcic_set_event_filter(void) { return 0; }
s32 btsnd_hcic_write_pin_type(void) { return 0; }
s32 btsnd_hcic_read_stored_key(void) { return 0; }
s32 btsnd_hcic_write_stored_key(void) { return 0; }
s32 btsnd_hcic_delete_stored_key(void) { return 0; }
s32 btsnd_hcic_change_name(void) { return 0; }
s32 btsnd_hcic_write_page_tout(void) { return 0; }
s32 btsnd_hcic_write_scan_enable(void) { return 0; }
s32 btsnd_hcic_write_pagescan_cfg(void) { return 0; }
s32 btsnd_hcic_write_inqscan_cfg(void) { return 0; }
s32 btsnd_hcic_write_auth_enable(void) { return 0; }
s32 btsnd_hcic_write_encr_mode(void) { return 0; }
s32 btsnd_hcic_write_dev_class(void) { return 0; }
s32 btsnd_hcic_write_auto_flush_tout(void) { return 0; }
s32 btsnd_hcic_set_host_buf_size(void) { return 0; }
s32 btsnd_hcic_write_link_super_tout(void) { return 0; }
s32 btsnd_hcic_write_cur_iac_lap(void) { return 0; }
s32 btsnd_hcic_read_local_ver(void) { return 0; }
s32 btsnd_hcic_read_local_features(void) { return 0; }
s32 btsnd_hcic_read_buffer_size(void) { return 0; }
s32 btsnd_hcic_read_bd_addr(void) { return 0; }
s32 btsnd_hcic_get_link_quality(void) { return 0; }
s32 btsnd_hcic_read_rssi(void) { return 0; }
s32 btsnd_hcic_set_afh_channels(void) { return 0; }
s32 btsnd_hcic_write_inqscan_type(void) { return 0; }
s32 btsnd_hcic_write_inquiry_mode(void) { return 0; }
s32 btsnd_hcic_write_pagescan_type(void) { return 0; }
s32 btsnd_hcic_vendor_spec_cmd(void) { return 0; }
