#include "types.h"
s32 l2cu_allocate_lcb(void) { return 0; }
s32 l2cu_release_lcb(void) { return 0; }
s32 l2cu_find_lcb_by_bd_addr(void) { return 0; }
s32 l2cu_find_lcb_by_handle(void) { return 0; }
s32 l2cu_get_conn_role(void) { return 0; }
s32 l2cu_build_header(void) { return 0; }
s32 l2cu_send_peer_cmd_reject(void) { return 0; }
s32 l2cu_send_peer_connect_req(void) { return 0; }
s32 l2cu_send_peer_connect_rsp(void) { return 0; }
s32 l2cu_reject_connection(void) { return 0; }
s32 l2cu_send_peer_config_req(void) { return 0; }
s32 l2cu_send_peer_config_rsp(void) { return 0; }
s32 l2cu_send_peer_config_rej(void) { return 0; }
s32 l2cu_send_peer_disc_req(void) { return 0; }
s32 l2cu_send_peer_disc_rsp(void) { return 0; }
s32 l2cu_send_peer_echo_req(void) { return 0; }
s32 l2cu_send_peer_echo_rsp(void) { return 0; }
s32 l2cu_send_peer_info_rsp(void) { return 0; }
s32 l2cu_allocate_ccb(void) { return 0; }
s32 l2cu_release_ccb(void) { return 0; }
s32 l2cu_find_ccb_by_cid(void) { return 0; }
s32 l2cu_allocate_rcb(void) { return 0; }
s32 l2cu_release_rcb(void) { return 0; }
s32 l2cu_find_rcb_by_psm(void) { return 0; }
s32 l2cu_process_peer_cfg_req(void) { return 0; }
s32 l2cu_process_peer_cfg_rsp(void) { return 0; }
s32 l2cu_process_our_cfg_req(void) { return 0; }
s32 l2cu_process_our_cfg_rsp(void) { return 0; }
s32 l2cu_device_reset(void) { return 0; }
s32 l2cu_create_conn(void) { return 0; }
s32 l2cu_create_conn_after_switch(void) { return 0; }
s32 l2cu_find_lcb_by_state(void) { return 0; }
s32 l2cu_lcb_disconnecting(void) { return 0; }
